# 1. Выгрузка данных

Читаю из .xlsx файла ссылки на блоггеров, чищу их и привожу к удобному виду.

In [5]:
import pandas as pd

df = pd.read_excel("bloggers.xlsx")
links = df["Unnamed: 1"].dropna().tolist()
print(links[:5])

['https://instagram.com/nike', 'https://instagram.com/apple', 'https://www.instagram.com/krrazalia?igsh=MWFvMG14cmI5am1xbA==', 'https://www.instagram.com/nev_pollyy?igsh=NzZydHlhY3gyMzBo', 'https://www.instagram.com/_crazy__unicorn__?igsh=MThjMmtxZ3dvazh2dQ==']

In [6]:
import re

def extract_username(link):
    link = str(link).strip()

    if link.startswith("@"):
        return link[1:]

    match = re.search(r"instagram\.com/([^/?]+)", link)
    if match:
        return match.group(1)

    return link

usernames = [extract_username(link) for link in links]

print(usernames[:10])

['nike', 'apple', 'krrazalia', 'nev_pollyy', '_crazy__unicorn__', 'demoiselle._.rie', 'shalafaeva.al', 'kristi_naxodka', 'yunglolaa', 'sha_obzor.wb']

In [17]:
usernames = usernames[0:13]+usernames[14::]

In [18]:
usernames

['nike',
 'apple',
 'krrazalia',
 'nev_pollyy',
 '_crazy__unicorn__',
 'demoiselle._.rie',
 'shalafaeva.al',
 'kristi_naxodka',
 'yunglolaa',
 'sha_obzor.wb',
 'daria_grogulenko',
 'llaurraiiam',
 'lv_yana_lv',
 'v.m.Beauty_blog',
 'miysta_fatt_',
 'juliar_r',
 '_kate_bruni',
 'jd_cosm',
 'habakher',
 'dddinaaaaaa',
 'janestetsiura',
 'ri_vls',
 '__aparina',
 'armlilitka',
 'rtini.a13',
 'aida.mixx',
 'bazhenova_alenaa',
 'anetboss_',
 '19.voron',
 'ninooochka2.0',
 'irinatitovaaa_',
 'kotova.live',
 'zari.ishikhovaa']

Для парсинга Инстаграмма использую Apify, они дают бесплатные \$5 в месяц, для двух запросов достаточно, я потратила \$1.17 для выгрузки постов и профиля

In [8]:
!pip install apify-client python-dotenv

Collecting apify-client
  Downloading apify_client-3.1.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)
Collecting colorama>=0.4.0 (from apify-client)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting impit~=0.13.0 (from apify-client)
  Downloading impit-0.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.9 kB)
Requirement already satisfied: more-itertools>=10.0.0 in /usr/local/lib/python3.12/dist-packages (from apify-client) (10.8.0)
Requirement already satisfied: pydantic>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from pydantic[email]>=2.11.0->apify-client) (2.13.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->pydantic[email]>=2.11.0->apify-client) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->pydantic[email]>=2.11.0->apify-client) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->pydantic[email]>=2.11.0->apify-client) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->pydantic[email]>=2.11.0->apify-client) (0.4.2)
Collecting email-validator>=2.0.0 (from pydantic[email]>=2.11.0->apify-client)
  Downloading email_validator-2.3.0-py3-none-any.whl.metadata (26 kB)
Collecting dnspython>=2.0.0 (from email-validator>=2.0.0->pydantic[email]>=2.11.0->apify-client)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: idna>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->pydantic[email]>=2.11.0->apify-client) (3.18)
Downloading apify_client-3.1.0-py3-none-any.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.4/149.4 kB 2.0 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading impit-0.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 21.6 MB/s eta 0:00:00
Downloading email_validator-2.3.0-py3-none-any.whl (35 kB)
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 26.1 MB/s eta 0:00:00
Installing collected packages: impit, dnspython, colorama, email-validator, apify-client
Successfully installed apify-client-3.1.0 colorama-0.4.6 dnspython-2.8.0 email-validator-2.3.0 impit-0.13.1

In [27]:
import os
from dotenv import load_dotenv
from apify_client import ApifyClient

load_dotenv()

client = ApifyClient("Ваш_apify_token")

In [28]:
run_input = {
    "directUrls": [
        f"https://www.instagram.com/{u}/"
        for u in usernames
    ],
    "resultsType": "posts",
    "resultsLimit": 20
}

In [29]:
run_input

{'directUrls': ['https://www.instagram.com/nike/',
  'https://www.instagram.com/apple/',
  'https://www.instagram.com/krrazalia/',
  'https://www.instagram.com/nev_pollyy/',
  'https://www.instagram.com/_crazy__unicorn__/',
  'https://www.instagram.com/demoiselle._.rie/',
  'https://www.instagram.com/shalafaeva.al/',
  'https://www.instagram.com/kristi_naxodka/',
  'https://www.instagram.com/yunglolaa/',
  'https://www.instagram.com/sha_obzor.wb/',
  'https://www.instagram.com/daria_grogulenko/',
  'https://www.instagram.com/llaurraiiam/',
  'https://www.instagram.com/lv_yana_lv/',
  'https://www.instagram.com/v.m.Beauty_blog/',
  'https://www.instagram.com/miysta_fatt_/',
  'https://www.instagram.com/juliar_r/',
  'https://www.instagram.com/_kate_bruni/',
  'https://www.instagram.com/jd_cosm/',
  'https://www.instagram.com/habakher/',
  'https://www.instagram.com/dddinaaaaaa/',
  'https://www.instagram.com/janestetsiura/',
  'https://www.instagram.com/ri_vls/',
  'https://www.instagram.com/__aparina/',
  'https://www.instagram.com/armlilitka/',
  'https://www.instagram.com/rtini.a13/',
  'https://www.instagram.com/aida.mixx/',
  'https://www.instagram.com/bazhenova_alenaa/',
  'https://www.instagram.com/anetboss_/',
  'https://www.instagram.com/19.voron/',
  'https://www.instagram.com/ninooochka2.0/',
  'https://www.instagram.com/irinatitovaaa_/',
  'https://www.instagram.com/kotova.live/',
  'https://www.instagram.com/zari.ishikhovaa/'],
 'resultsType': 'posts',
 'resultsLimit': 20}

In [30]:
run = client.actor("shu8hvrXbJbY3Eb9W").call(run_input=run_input)

[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> Status: RUNNING, Message:
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:02.611Z ACTOR: Pulling container image of build as7z3KRU3PF0ai0MU from registry.
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:02.613Z ACTOR: Creating container.
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:02.657Z ACTOR: Starting container.
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:02.658Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:03.309Z INFO  System info {"apifyVersion":"3.6.0","apifyClientVersion":"2.22.2","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v24.18.0"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:03.454Z INFO  [Status message]: Starting the scraper with 33 direct URL(s)
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> Status: RUNNING, Message: Starting the crawler.
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:03.642Z INFO  CheerioCrawler: Starting the crawler.
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:04.800Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:04.801Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"HG4UU3fm44ATdKz","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=demoiselle._.rie","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.057Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.065Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"cVpQdfUqPccT9rm","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=_kate_bruni","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.069Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.069Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"tAOM61TdQAH25Vr","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=juliar_r","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.088Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.089Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"dmjN8cZfuR4ZjcU","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=habakher","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.276Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Retrying after error: Page Not Found • Instagram
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.277Z     at preRouteErrorCheck (file:///usr/src/app/dist/index.js:38:733069) {"id":"DVklQ5hgCMWzrwV","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=nev_pollyy","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.325Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.326Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"UGWP89d7nofP0Az","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=sha_obzor.wb","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.569Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.569Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"O50JYgJlzfc3M1G","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=kotova.live","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.765Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.766Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"pDhHOkJ3VeDKBoS","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=19.voron","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.852Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Retrying after error: Page Not Found • Instagram
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.853Z     at preRouteErrorCheck (file:///usr/src/app/dist/index.js:38:733069) {"id":"hxmK61lB49d1RPO","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=_crazy__unicorn__","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.859Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.860Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"ca5pFdorXbG6eHP","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=llaurraiiam","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.862Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.863Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"LxcIYwbENV8hwne","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=__aparina","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.871Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Retrying after error: Page Not Found • Instagram
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:05.872Z     at preRouteErrorCheck (file:///usr/src/app/dist/index.js:38:733069) {"id":"2uUxqvTPNf8YBXf","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=rtini.a13","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.194Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.195Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"zyWofuv10LUz9nu","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=zari.ishikhovaa","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.390Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.391Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"bEve8DOMVZXqv1N","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=dddinaaaaaa","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.394Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.395Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"9t96COMJwX1WtwS","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=kristi_naxodka","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.422Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.423Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"nO0qIvsjD8AB6kZ","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=yunglolaa","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.485Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.486Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"RQN7a48lfs6Z0L8","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=janestetsiura","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.528Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.529Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"iN9G5YjvgxvTLv9","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=ninooochka2.0","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.571Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.572Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"n9j1bHhlcxxw3L2","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=irinatitovaaa_","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.847Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:06.847Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"w2OHigbbLQDJDTv","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=ri_vls","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.013Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.014Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"xQMn2QwZgkdBagp","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=bazhenova_alenaa","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.263Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request got blocked. Will retry with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.263Z     at handlePostsFeed (file:///usr/src/app/dist/index.js:38:688072) {"id":"RDER1AMCfBcIhDE","url":"https://www.instagram.com/graphql/query/?doc_id=7950326061742207&variables=%7B%22id%22%3A%229288139041%22%2C%22first%22%3A12%7D","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.579Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Retrying after error: Page Not Found • Instagram
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.579Z     at preRouteErrorCheck (file:///usr/src/app/dist/index.js:38:733069) {"id":"PZpEeaScIa97KVr","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=miysta_fatt_","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.853Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.854Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"TYiOJU8H3g0EcFq","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=anetboss_","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:07.879Z INFO  NO RESULTS: zero public posts for https://www.instagram.com/shalafaeva.al/ within the given requirements
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:08.722Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/demoiselle._.rie/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:10.088Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/habakher/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:10.134Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DMaNceAIK_9","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:10.253Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/rtini.a13/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:10.566Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DEuSw-5tWNT","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:10.612Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/__aparina/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.031Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.031Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"iN9G5YjvgxvTLv9","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=ninooochka2.0","retryCount":2}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.062Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/ri_vls/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.098Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/nev_pollyy/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.233Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/_crazy__unicorn__/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.634Z INFO  web_profile_info returned HTTP 400, using route definition and details by id instead {"username":"yunglolaa"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.837Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/miysta_fatt_/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:11.956Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DMNaJlVo9Y-","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:12.239Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DJO8ZbZsN0e","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:12.820Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DMNl94xoryB","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:12.978Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DMdJGneIFdR","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.158Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. BLOCKED
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.159Z     at handleRestrictedPost (file:///usr/src/app/dist/index.js:38:647202) {"id":"SdWZlO5JhhsMQwz","url":"https://www.instagram.com/p/DQE-AbnDBwA","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.245Z INFO  Resolved profile ID from route definition {"username":"yunglolaa","profileId":"5769346152"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.277Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DQE9zkhDGtE","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.321Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DbRdeuYIQ6K","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.521Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DLqJ2cVsb_L","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.545Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DbObJ5wo1Af","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:13.741Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DbJYpcKInxh","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:14.051Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. BLOCKED
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:14.052Z     at handleRestrictedPost (file:///usr/src/app/dist/index.js:38:647202) {"id":"2amk6NlApPQazDR","url":"https://www.instagram.com/p/DbMK0tpIe-N","retryCount":1}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:14.180Z WARN  Page Not Found • Instagram {"inputUrl":"https://www.instagram.com/irinatitovaaa_/"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> Status: RUNNING, Message: Crawled 43/163 pages, 0 failed requests, desired concurrency 160.
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:14.225Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DbJRwJxIqfZ","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:15.343Z INFO  [END-OF-RESULTS]: krrazalia confirmed end of results at pos 21
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:15.449Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DLm7MbfsUhZ","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:15.646Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"Da0SiSHKwur","docId":"7341532402634560"}
[apify.instagram-scraper runId:9bnZMTANfr2SHREYH] -> 2026-07-27T21:14:15.717Z WARN  post-details: media metrics GraphQL doc_id may have changed {"shortCode":"DLHrB8jIRoX","docId":"7341532402634560"}

In [35]:
dataset_id = run.default_dataset_id

In [37]:
dataset = client.dataset(dataset_id)

items = list(dataset.iterate_items())

print(len(items))
print(items[1])

411
{'url': 'https://www.instagram.com/demoiselle._.rie/', 'username': 'demoiselle._.rie', 'error': 'not_found', 'errorDescription': 'Post does not exist'}

In [41]:
from pprint import pprint

pprint(items[0])

{'error': 'no_items',
 'errorDescription': 'Empty or private data for provided input',
 'inputUrl': 'https://www.instagram.com/shalafaeva.al/',
 'requestErrorMessages': [],
 'url': 'https://www.instagram.com/shalafaeva.al/'}

Оставляю только валидные запросы

In [42]:
valid_items = [x for x in items if "error" not in x]

print(f"Всего: {len(items)}")
print(f"Успешно: {len(valid_items)}")

if valid_items:
    from pprint import pprint
    pprint(valid_items[0])

Всего: 411
Успешно: 398
{'alt': 'Video by Дарья | Обзоры с WILDBERRIES | женственность on July 22, '
        '2025.',
 'audioUrl': 'https://instagram.fcae1-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQMvf6xipe6SK1nrhJ1eZynOiAoxtcdLbZR1-hOOUsOD9wsNP4PLBj4xRt3-YG_6MRNbjKYij9W3criJpsK5xsWw.mp4?_nc_cat=101&_nc_oc=Adqt14RKoj830MxJtELMKRRWnEtwPlKHP1pGQZ5IHsMIhL_ZiSgFrdToaADb_t7eiZA&_nc_sid=9ca052&_nc_ht=instagram.fcae1-1.fna.fbcdn.net&_nc_ohc=GmmXhGVCfkMQ7kNvwH4raVk&efg=eyJ2ZW5jb2RlX3RhZyI6ImlnLXhwdmRzLmNsaXBzLmlnd3d3LUMzLmRhc2hfbG5faGVhYWNfdmJyM19hdWRpbyIsInZpZGVvX2lkIjpudWxsLCJvaWxfdXJsZ2VuX2FwcF9pZCI6OTM2NjE5NzQzMzkyNDU5LCJjbGllbnRfbmFtZSI6ImlnIiwieHB2X2Fzc2V0X2lkIjoyMjA2OTg1NjY2NDgwMTUxLCJhc3NldF9hZ2VfZGF5cyI6MzcwLCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6OSwiYml0cmF0ZSI6NjkxNDUsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=uTp9WSj2im0OrSsfp1yyFg&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQAznHVZyyeV5e6TTscu_YJ3kEiY-5oIbB_RujZjbEaYbQ&oe=6A69B975',
 'caption': 'Девочки, мы?🤣 \n'
            'На видео продукты от @mixit_ru 🩷\n'
            '\n'
            'Артикул на обертывание ВБ:👇🏼\n'
            '#ww114906',
 'childPosts': [],
 'commentsCount': 0,
 'dimensionsHeight': 2054,
 'dimensionsWidth': 1158,
 'displayUrl': 'https://instagram.fcae1-1.fna.fbcdn.net/v/t51.82787-15/521414295_18333724807200212_329278958759238367_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=110&ig_cache_key=MzY4MjMxNDc3NjI5MzE5MTY3NzE4MzMzNzI0ODA0MjAwMjEy.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjExNTguc2RyLnZpZGVvX2RlZmF1bHRfY292ZXJfZnJhbWUuQzMifQ%3D%3D&_nc_ohc=cfLU5ot71lkQ7kNvwHgm6ib&_nc_oc=Adr7QpQL9kyYWW3YFny6B_qLSsscafeqv51V1NdE-Au9G3RS3ywjuvw3igrataX3CIQ&_nc_zt=23&_nc_ht=instagram.fcae1-1.fna&_nc_gid=uTp9WSj2im0OrSsfp1yyFg&_nc_ss=7ca8c&oh=00_AQDGDtlwfN4HzyYHzo-2P3o6ZJneoQ9Z63DMi56LtTGx7A&oe=6A6DAB3C',
 'firstComment': '',
 'hashtags': ['ww114906'],
 'id': '3682314776293191677',
 'images': [],
 'inputUrl': 'https://www.instagram.com/daria_grogulenko/',
 'isCommentsDisabled': False,
 'latestComments': [],
 'likesCount': 8,
 'locationId': 115085015172389,
 'locationName': 'Moscow, Russia',
 'mentions': ['mixit_ru'],
 'originalHeight': 640,
 'originalWidth': 360,
 'ownerFullName': 'Дарья | Обзоры с WILDBERRIES | женственность',
 'ownerId': '6006968211',
 'ownerUsername': 'daria_grogulenko',
 'paidPartnership': False,
 'productType': 'clips',
 'shortCode': 'DMaNceAIK_9',
 'timestamp': '2025-07-22T12:10:00.000Z',
 'type': 'Video',
 'url': 'https://www.instagram.com/p/DMaNceAIK_9/',
 'videoUrl': 'https://instagram.fcae1-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQPtJA29VpdfewppxE-en-0oi3igK1-uYY6G4gGDYRJ-wPqPcNiLfcukzFZ9QKCqhNjORtn3acX4TYcCDrtd04wmogbWmf4MAabFmbw.mp4?_nc_cat=105&_nc_oc=AdqopNDfLc8YIjtuZ1bb_p--fLUrlVuFM4xK2eeLEranLUwThMqGmpCi8hJ4nw3yebE&_nc_sid=5e9851&_nc_ht=instagram.fcae1-1.fna.fbcdn.net&_nc_ohc=1d5Q9-hWe1sQ7kNvwE1Y1qi&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuMzYwLmRhc2hfYmFzZWxpbmVfM192MSIsInhwdl9hc3NldF9pZCI6MjIwNjk4NTY2NjQ4MDE1MSwiYXNzZXRfYWdlX2RheXMiOjM3MCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjksInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=d1311393c19648a3&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9FQjQ2MjMxMUNFN0Y2QzFEQUVCN0I2N0UyREI5MkNBRV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYR2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8xOTAzODQzNTYzNjgxODQwXzQyNTk0MDU0NzUxODgyMTQ4MjIubXA0FQICyAESACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJq6g5sq8z-sHFQIoAkMzLBdAI3dLxqfvnhgSZGFzaF9iYXNlbGluZV8zX3YxEQB1_gdl5p0BAA&_nc_gid=uTp9WSj2im0OrSsfp1yyFg&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQAcj2v5ITsizHV9q-JKu0Dm0B-lK5LEEoimG6NHF5m4cQ&oe=6A69B35A',
 'videoViewCount': 1353}

In [43]:
from collections import defaultdict

bloggers = defaultdict(list)

for post in valid_items:
    bloggers[post["ownerUsername"]].append(post)

print(len(bloggers))

24

In [101]:
bloggers["daria_grogulenko"]

[{'id': '3682314776293191677',
  'type': 'Video',
  'shortCode': 'DMaNceAIK_9',
  'caption': 'Девочки, мы?🤣 \nНа видео продукты от @mixit_ru 🩷\n\nАртикул на обертывание ВБ:👇🏼\n#ww114906',
  'hashtags': ['ww114906'],
  'mentions': ['mixit_ru'],
  'url': 'https://www.instagram.com/p/DMaNceAIK_9/',
  'commentsCount': 0,
  'firstComment': '',
  'latestComments': [],
  'dimensionsHeight': 2054,
  'dimensionsWidth': 1158,
  'displayUrl': 'https://instagram.fcae1-1.fna.fbcdn.net/v/t51.82787-15/521414295_18333724807200212_329278958759238367_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=110&ig_cache_key=MzY4MjMxNDc3NjI5MzE5MTY3NzE4MzMzNzI0ODA0MjAwMjEy.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjExNTguc2RyLnZpZGVvX2RlZmF1bHRfY292ZXJfZnJhbWUuQzMifQ%3D%3D&_nc_ohc=cfLU5ot71lkQ7kNvwHgm6ib&_nc_oc=Adr7QpQL9kyYWW3YFny6B_qLSsscafeqv51V1NdE-Au9G3RS3ywjuvw3igrataX3CIQ&_nc_zt=23&_nc_ht=instagram.fcae1-1.fna&_nc_gid=uTp9WSj2im0OrSsfp1yyFg&_nc_ss=7ca8c&oh=00_AQDGDtlwfN4HzyYHzo-2P3o6ZJneoQ9Z63DMi56LtTGx7A&oe=6A6DAB3C',
  'images': [],
  'videoUrl': 'https://instagram.fcae1-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQPtJA29VpdfewppxE-en-0oi3igK1-uYY6G4gGDYRJ-wPqPcNiLfcukzFZ9QKCqhNjORtn3acX4TYcCDrtd04wmogbWmf4MAabFmbw.mp4?_nc_cat=105&_nc_oc=AdqopNDfLc8YIjtuZ1bb_p--fLUrlVuFM4xK2eeLEranLUwThMqGmpCi8hJ4nw3yebE&_nc_sid=5e9851&_nc_ht=instagram.fcae1-1.fna.fbcdn.net&_nc_ohc=1d5Q9-hWe1sQ7kNvwE1Y1qi&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuMzYwLmRhc2hfYmFzZWxpbmVfM192MSIsInhwdl9hc3NldF9pZCI6MjIwNjk4NTY2NjQ4MDE1MSwiYXNzZXRfYWdlX2RheXMiOjM3MCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjksInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=d1311393c19648a3&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9FQjQ2MjMxMUNFN0Y2QzFEQUVCN0I2N0UyREI5MkNBRV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYR2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8xOTAzODQzNTYzNjgxODQwXzQyNTk0MDU0NzUxODgyMTQ4MjIubXA0FQICyAESACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJq6g5sq8z-sHFQIoAkMzLBdAI3dLxqfvnhgSZGFzaF9iYXNlbGluZV8zX3YxEQB1_gdl5p0BAA&_nc_gid=uTp9WSj2im0OrSsfp1yyFg&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQAcj2v5ITsizHV9q-JKu0Dm0B-lK5LEEoimG6NHF5m4cQ&oe=6A69B35A',
  'likesCount': 8,
  'videoViewCount': 1353,
  'timestamp': '2025-07-22T12:10:00.000Z',
  'childPosts': [],
  'locationName': 'Moscow, Russia',
  'locationId': 115085015172389,
  'ownerFullName': 'Дарья | Обзоры с WILDBERRIES | женственность',
  'ownerUsername': 'daria_grogulenko',
  'ownerId': '6006968211',
  'productType': 'clips',
  'paidPartnership': False,
  'isCommentsDisabled': False,
  'inputUrl': 'https://www.instagram.com/daria_grogulenko/',
  'originalHeight': 640,
  'originalWidth': 360,
  'audioUrl': 'https://instagram.fcae1-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQMvf6xipe6SK1nrhJ1eZynOiAoxtcdLbZR1-hOOUsOD9wsNP4PLBj4xRt3-YG_6MRNbjKYij9W3criJpsK5xsWw.mp4?_nc_cat=101&_nc_oc=Adqt14RKoj830MxJtELMKRRWnEtwPlKHP1pGQZ5IHsMIhL_ZiSgFrdToaADb_t7eiZA&_nc_sid=9ca052&_nc_ht=instagram.fcae1-1.fna.fbcdn.net&_nc_ohc=GmmXhGVCfkMQ7kNvwH4raVk&efg=eyJ2ZW5jb2RlX3RhZyI6ImlnLXhwdmRzLmNsaXBzLmlnd3d3LUMzLmRhc2hfbG5faGVhYWNfdmJyM19hdWRpbyIsInZpZGVvX2lkIjpudWxsLCJvaWxfdXJsZ2VuX2FwcF9pZCI6OTM2NjE5NzQzMzkyNDU5LCJjbGllbnRfbmFtZSI6ImlnIiwieHB2X2Fzc2V0X2lkIjoyMjA2OTg1NjY2NDgwMTUxLCJhc3NldF9hZ2VfZGF5cyI6MzcwLCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6OSwiYml0cmF0ZSI6NjkxNDUsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=uTp9WSj2im0OrSsfp1yyFg&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQAznHVZyyeV5e6TTscu_YJ3kEiY-5oIbB_RujZjbEaYbQ&oe=6A69B975',
  'alt': 'Video by Дарья | Обзоры с WILDBERRIES | женственность on July 22, 2025.'},
 {'id': '3543852487699424083',
  'type': 'Video',
  'shortCode': 'DEuSw-5tWNT',
  'caption': '@daria_grogulenko больше обзоров у меня в профиле!🤍\n\n📎Артикул 299373468',
  'hashtags': [],
  'mentions': ['daria_grogulenko'],
  'url': 'https://www.instagram.com/p/DEuSw-5tWNT/',
  'commentsCount': 1,
  'firstComment': '😍😍',
  'latestComments': [{'id': '18058291762804893',
    'text': '😍😍',
    'ownerUsername': 'just.marikaa',
    'ownerProfilePicUrl': 'https://scontent-phl2-1.cdninstagram.com/v/t51.82787-19/598251826_17896062636360015_6931746563478269355_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=101&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDQwLkMzIn0%3D&_nc_ohc=P65zm_dmRbUQ7kNvwFqFAjT&_nc_oc=Adrjm52XH5EpFrwnIPfTMssuiUVzns9aswF26Mfth_X4zIZDt27OGKtPP-nIWswEaC9bSa5WnH4WuwyvMwmeyCnA&_nc_zt=24&_nc_ht=scontent-phl2-1.cdninstagram.com&_nc_gid=OYQBvhqfRojo30PcOIr37g&_nc_ss=7ca8c&oh=00_AQB_psn7uVAaNUCiSksGz0sJ0dG9fEdOp1iM9WdnbqDsGw&oe=6A6DA2F3',
    'timestamp': '2025-01-22T17:35:07.000Z',
    'repliesCount': None,
    'replies': None,
    'likesCount': 0,
    'owner': {'username': 'just.marikaa',
     'profile_pic_url': 'https://scontent-phl2-1.cdninstagram.com/v/t51.82787-19/598251826_17896062636360015_6931746563478269355_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=101&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDQwLkMzIn0%3D&_nc_ohc=P65zm_dmRbUQ7kNvwFqFAjT&_nc_oc=Adrjm52XH5EpFrwnIPfTMssuiUVzns9aswF26Mfth_X4zIZDt27OGKtPP-nIWswEaC9bSa5WnH4WuwyvMwmeyCnA&_nc_zt=24&_nc_ht=scontent-phl2-1.cdninstagram.com&_nc_gid=OYQBvhqfRojo30PcOIr37g&_nc_ss=7ca8c&oh=00_AQB_psn7uVAaNUCiSksGz0sJ0dG9fEdOp1iM9WdnbqDsGw&oe=6A6DA2F3',
     'is_verified': False,
     'id': '70996400014',
     'full_name': None,
     'is_mentionable': None,
     'is_private': None,
     'profile_pic_id': None,
     'latest_reel_media': None}}],
  'dimensionsHeight': 2054,
  'dimensionsWidth': 1158,
  'displayUrl': 'https://scontent-phl2-1.cdninstagram.com/v/t51.71878-15/502973292_585014064193957_1666322371586233005_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=100&ig_cache_key=MzU0Mzg1MjQ4NzY5OTQyNDA4Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjExNTguc2RyLnZpZGVvX2RlZmF1bHRfY292ZXJfZnJhbWUuQzMifQ%3D%3D&_nc_ohc=KSMB3gnZRssQ7kNvwF871cL&_nc_oc=AdrA9HlVFoHMnGFWSxd-eh_lFGvPuylzXh_YQ72ZDwtyvgMoqwXp-O92f8IHVMeziPzvyLkg4UHAHSWSB3RXAVgw&_nc_zt=23&_nc_ht=scontent-phl2-1.cdninstagram.com&_nc_gid=OYQBvhqfRojo30PcOIr37g&_nc_ss=7ca8c&oh=00_AQB3tvpC1CNPzorEIpqt1RCGOAwVAFF4RiMcYjF4PwnDZQ&oe=6A6D9961',
  'images': [],
  'videoUrl': 'https://scontent-phl2-1.cdninstagram.com/o1/v/t2/f2/m367/AQPLNs2jP-JZWWBxb_7tu4vIAjxIeYko8QKwkTzuBB1mwJCGQHnKfDNGpHoDVEkL8PIMkwjcWU3Iwmc4OremO460OUV8keClpwKSlLY.mp4?_nc_cat=105&_nc_sid=5e9851&_nc_ht=scontent-phl2-1.cdninstagram.com&_nc_ohc=bKrtI8J-cFEQ7kNvwEPmqj7&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6NDk0MzQzMjY2NTk0MzcxLCJhc3NldF9hZ2VfZGF5cyI6NTYxLCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6MTIsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=43dc6a4c51065ed2&_nc_vs=HBksFQIYQGlnX2VwaGVtZXJhbC80QjRFMjA2RjZEQURBRUQ5MjRBMUQyMjFDOTgxM0U4N192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYR2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8xMzA5NTg5ODAzNTAwMjI3XzYwMDM1ODkzOTI0NzQ1Mzg5OTEubXA0FQICyAESACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJoa566zI5uABFQIoAkMzLBdAKUQYk3S8ahgSZGFzaF9iYXNlbGluZV8xX3YxEQB1_gdl5p0BAA&_nc_gid=OYQBvhqfRojo30PcOIr37g&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQBYoeMYrO-6yDF20YPZTibODLxdSiA-Jxu5QZpfHiLUmg&oe=6A6DA63A',
  'likesCount': 25,
  'videoViewCount': 1052,
  'timestamp': '2025-01-12T11:10:25.000Z',
  'childPosts': [],
  'locationName': 'Москва, ВДНХ',
  'locationId': 499933547,
  'ownerFullName': 'Дарья | Обзоры с WILDBERRIES | женственность',
  'ownerUsername': 'daria_grogulenko',
  'ownerId': '6006968211',
  'productType': 'clips',
  'paidPartnership': False,
  'isPinned': True,
  'isCommentsDisabled': False,
  'inputUrl': 'https://www.instagram.com/daria_grogulenko/',
  'originalHeight': 1280,
  'originalWidth': 720,
  'audioUrl': 'https://scontent-phl2-1.cdninstagram.com/o1/v/t2/f2/m86/AQMQHdakfk_p1Oe0OgNLION70l1dSM_7eMiRH3_niuvTM52qa5zJPq2Z0nnYl_sgZMVzgVDluH8hAnDlu3OWOiOT.mp4?_nc_cat=106&_nc_sid=9ca052&_nc_ht=scontent-phl2-1.cdninstagram.com&_nc_ohc=OTZr9uWKKvMQ7kNvwHBXo-G&efg=eyJ2ZW5jb2RlX3RhZyI6ImlnLXhwdmRzLmNsaXBzLmlnd3d3LUMzLmRhc2hfbG5faGVhYWNfdmJyM19hdWRpbyIsInZpZGVvX2lkIjpudWxsLCJvaWxfdXJsZ2VuX2FwcF9pZCI6OTM2NjE5NzQzMzkyNDU5LCJjbGllbnRfbmFtZSI6ImlnIiwieHB2X2Fzc2V0X2lkIjo0OTQzNDMyNjY1OTQzNzEsImFzc2V0X2FnZV9kYXlzIjo1NjEsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoxMiwiYml0cmF0ZSI6ODQzOTUsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=OYQBvhqfRojo30PcOIr37g&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQDvZguSchu8GgCkaPFKALl0ryeq2_GKwx5zK4R5Dlu6Dw&oe=6A699D98',
  'alt': 'Video by Дарья | Обзоры с WILDBERRIES | женственность on January 12, 2025.'},
 {'id': '3678711478407648830',
  'type': 'Video',
  'shortCode': 'DMNaJlVo9Y-',
  'caption': 'А как вы пользуетесь скрабом?\nАртикул на скраб от @mixit_ru 🫶🏻👇🏼\n\nВБ: #ww114862 \nОзон: 1843395876\n\n@daria_grogulenko больше обзоров у меня в профиле, подпишись, чтобы не пропустить🫶🏻\n#находкивб #вб #распаковка #юмор',
  'hashtags': ['ww114862', 'находкивб', 'вб', 'распаковка', 'юмор'],
  'mentions': ['mixit_ru', 'daria_grogulenko'],
  'url': 'https://www.instagram.com/p/DMNaJlVo9Y-/',
  'commentsCount': 0,
  'firstComment': '',
  'latestComments': [],
  'dimensionsHeight': 1826,
  'dimensionsWidth': 1030,
  'displayUrl': 'https://instagram.fyaw1-1.fna.fbcdn.net/v/t51.82787-15/519970535_18333153445200212_5958946637593543488_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=107&_nc_map=urlgen_bucketless&ig_cache_key=MzY3ODcxMTQ3ODQwNzY0ODgzMDE4MzMzMTUzNDM5MjAwMjEy.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjEwMzAuc2RyLnZpZGVvX2RlZmF1bHRfY292ZXJfZnJhbWUuQzMifQ%3D%3D&_nc_ohc=WlCUzupO6MYQ7kNvwEjhf2-&_nc_oc=AdrXTznTueMlcAuv0m_Y5V4bz2kXB9v6wVO5XUwJYyDU_J6EzJrtHQRT2hNnufJMtdk&_nc_zt=23&_nc_ht=instagram.fyaw1-1.fna&_nc_gid=ruyb9w4aT198LTv5eSkiuw&_nc_ss=72a8c&oh=00_AQBDEMweO_vxiYN5Z6FcD1ONpGI50aaAVhew-_l5B4iOYg&oe=6A6D846C',
  'images': [],
  'videoUrl': 'https://instagram.fyaw1-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQNmla-hpwMgwPi3CHWSS5vJGEgOjuZKPh20SmgKTVK8lQI3tJ5rPQGJqi5AoInk3dncti5GnMOsRM3fzkfH7iD2zPw4DRhnlgaZ1pQ.mp4?_nc_cat=111&_nc_oc=AdqxBPvshao1TARe3b-auPIl8rEGMAzydWjiPoM4cXSMGJPZ3uEdZMuqC5MqaFEtAgk&_nc_sid=5e9851&_nc_ht=instagram.fyaw1-1.fna.fbcdn.net&_nc_ohc=Lv_1BFk5moAQ7kNvwHLK9co&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuMzYwLmRhc2hfYmFzZWxpbmVfM192MSIsInhwdl9hc3NldF9pZCI6NzIxMDA5Mjg0MDc1ODA2LCJhc3NldF9hZ2VfZGF5cyI6Mzc1LCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6MTksInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=b73a4699cd3401cd&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9CNTQxNjMwQTQ1RDFGMTA2QkEzNjlENkQ3MkVDRUM5MF92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYR2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8xNDEwMDIxMDM2Nzg0NTI0XzE5OTQwOTY3MjYyOTA4NDI4MjcubXA0FQICyAESACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJrzEjuSh8McCFQIoAkMzLBdAMwhysCDEnBgSZGFzaF9iYXNlbGluZV8zX3YxEQB1_gdl5p0BAA&_nc_gid=ruyb9w4aT198LTv5eSkiuw&_nc_ss=72a8c&_nc_map=urlgen_bucketless&_nc_zt=28&oh=00_AQCBUNnqtO2bGBQnxLz_SNSmsg3t2WbBnzOjxwDPJ9XjIg&oe=6A698F88',
  'likesCount': 5,
  'videoViewCount': 38,
  'timestamp': '2025-07-17T12:50:34.000Z',
  'childPosts': [],
  'locationName': 'Москва • Moscow',
  'locationId': 108889350634961,
  'ownerFullName': 'Дарья | Обзоры с WILDBERRIES | женственность',
  'ownerUsername': 'daria_grogulenko',
  'ownerId': '6006968211',
  'productType': 'clips',
  'paidPartnership': False,
  'taggedUsers': [{'full_name': 'MIXIT',
    'id': '1266587057',
    'is_verified': True,
    'profile_pic_url': 'https://scontent.cdninstagram.com/v/t51.2885-19/488802286_984395557131909_5715933892252572109_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=1&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=gNcIwPlTvIcQ7kNvwE-dSeN&_nc_oc=AdqhW5Jc4VyCB5DvQet7EDg6xKSL3wUhNqqLQzBgcYZBtCBFRH7YSC1yF0BWl7sORB0&_nc_zt=24&_nc_ht=scontent.cdninstagram.com&_nc_ss=72a8c&oh=00_AQAanot6csBuIt-yzK5KrZWuHoMlxolNLn9cCRgGRQS_Mw&oe=6A6DAAB9',
    'username': 'mixit_ru'}],
  'isCommentsDisabled': False,
  'inputUrl': 'https://www.instagram.com/daria_grogulenko/',
  'originalHeight': 640,
  'originalWidth': 360,
  'audioUrl': 'https://instagram.fyhz1-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQO8j7UopDEYUj7qNMQQBMDOxJLag7SrALZ17dptlSZ_zK01_ZVWUuxwc-x7LUgjlbTnZEz081Z_H3zKce_qhfPK.mp4?_nc_cat=111&_nc_oc=Adq5b5QSWGdeci-l5R7MSX5kBn5fS8aceBp9FzzaDMgkKpsKKDpvTx3AVp0hAW35SsE&_nc_sid=9ca052&_nc_ht=instagram.fyhz1-1.fna.fbcdn.net&_nc_ohc=FZAHMKeDMUUQ7kNvwFpZtxg&efg=eyJ2ZW5jb2RlX3RhZyI6ImlnLXhwdmRzLmNsaXBzLmlnd3d3LUMzLmRhc2hfbG5faGVhYWNfdmJyM19hdWRpbyIsInZpZGVvX2lkIjpudWxsLCJvaWxfdXJsZ2VuX2FwcF9pZCI6OTM2NjE5NzQzMzkyNDU5LCJjbGllbnRfbmFtZSI6ImlnIiwieHB2X2Fzc2V0X2lkIjo3MjEwMDkyODQwNzU4MDYsImFzc2V0X2FnZV9kYXlzIjozNzUsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoxOSwiYml0cmF0ZSI6NjcxNzYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=ruyb9w4aT198LTv5eSkiuw&_nc_ss=72a8c&_nc_map=urlgen_bucketless&_nc_zt=28&oh=00_AQB9-Syhhe-DI8K7fNnnci7J9RQxMXsg1iWjBKVf6rZGHw&oe=6A698C8F',
  'alt': 'Video by Дарья | Обзоры с WILDBERRIES | женственность on July 17, 2025.'},
 {'id': '3625100380279463198',
  'type': 'Video',
  'shortCode': 'DJO8ZbZsN0e',
  'caption': '@daria_grogulenko больше обзоров у меня в профиле!🤍\n\n#вб #распаковка #образ #стиль',
  'hashtags': ['вб', 'распаковка', 'образ', 'стиль'],
  'mentions': ['daria_grogulenko'],
  'url': 'https://www.instagram.com/p/DJO8ZbZsN0e/',
  'commentsCount': 0,
  'firstComment': '',
  'latestComments': [],
  'dimensionsHeight': 2080,
  'dimensionsWidth': 1170,
  'displayUrl': 'https://instagram.fldb3-1.fna.fbcdn.net/v/t51.75761-15/495978150_18324401401200212_5410660768527060368_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=101&ig_cache_key=MzYyNTEwMDM4MDI3OTQ2MzE5ODE4MzI0NDAxMzk1MjAwMjEy.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjExNzAuc2RyLnZpZGVvX2RlZmF1bHRfY292ZXJfZnJhbWUuQzMifQ%3D%3D&_nc_ohc=VkSBlLoM2X4Q7kNvwGtojpj&_nc_oc=Adpz27OlI59Axdq2hdwtrt3DZ5tRJe76FaC07mkRBUAqNGREcsIUxx8KZ5FgZmsQmw0&_nc_zt=23&_nc_ht=instagram.fldb3-1.fna&_nc_gid=BBInXT23pApv1zdZ-PzS-g&_nc_ss=72a8c&oh=00_AQAk98tCIAUQItXJ2jyeAG7H7pUA9CDEF0DSdIbs2exPYw&oe=6A6D95D3',
  'images': [],
  'videoUrl': 'https://instagram.fldb3-1.fna.fbcdn.net/o1/v/t2/f2/m367/AQOjSJtfwbSMtYa0Ty27rYDBsjX0dNZtVHLmVEeNpt1uCnixS_dNtIIid_zc9CdqrkUoZpx9mzurF3Ms5Q9yI02lWLlrdKd184KlsyQ.mp4?_nc_cat=102&_nc_oc=AdokoQkZyqkPBHcrsICU5TH3ZeBVH6PsjB1hl38-191R0Q5rrKWs4u-Tq9WpgsRYm8Y&_nc_sid=5e9851&_nc_ht=instagram.fldb3-1.fna.fbcdn.net&_nc_ohc=VDWc25K8tl4Q7kNvwF1fEkI&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTg5NTM2MDYyMTI4MDE1NywiYXNzZXRfYWdlX2RheXMiOjQ0OSwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjEyLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=d4b085d7958c4592&_nc_vs=HBksFQIYQGlnX2VwaGVtZXJhbC8yMTQ4MTEyQ0U1NzRBODMxRTNDOEQ0MzA3QzlDMzg4N192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYR2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8yMDQ0MDgyMjY2MDg0Mjk4XzUxNDEzMjM3Mjc0NDc4MjM1NTYubXA0FQICyAESACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJrru64jB9N0GFQIoAkMzLBdAKN2yLQ5WBBgSZGFzaF9iYXNlbGluZV8xX3YxEQB1_gdl5p0BAA&_nc_gid=BBInXT23pApv1zdZ-PzS-g&_nc_ss=72a8c&_nc_zt=28&oh=00_AQD4V9xBR6IvMe6ajuiMcSpT-mJM0eelamMq_gQ0mkLhdQ&oe=6A6D9307',
  'likesCount': 8,
  'videoViewCount': 727,
  'timestamp': '2025-05-04T13:35:36.000Z',
  'childPosts': [],
  'locationName': 'Москва • Moscow',
  'locationId': 108889350634961,
  'ownerFullName': 'Дарья | Обзоры с WILDBERRIES | женственность',
  'ownerUsername': 'daria_grogulenko',
  'ownerId': '6006968211',
  'productType': 'clips',
  'paidPartnership': False,
  'isPinned': True,
  'isCommentsDisabled': False,
  'inputUrl': 'https://www.instagram.com/daria_grogulenko/',
  'originalHeight': 1280,
  'originalWidth': 720,
  'audioUrl': 'https://instagram.fldb3-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQPqDWqhCKI-Hcn1Xl0J3Yh-HaqVNiYtdrFzFqmh6C4PyKQ3Offyd8ikOLXQrTFQW_lSfAyBN9XFtQBCogwKqwfI.mp4?_nc_cat=109&_nc_oc=AdpMBhOtPbxsWt1AeFCrPKfm5-BdQvBMdNe9ZpPuSevXfOF23NEN0ck3llMxm8yuQlo&_nc_sid=9ca052&_nc_ht=instagram.fldb3-1.fna.fbcdn.net&_nc_ohc=MwKcAUGqYMwQ7kNvwEjK3o4&efg=eyJ2ZW5jb2RlX3RhZyI6ImlnLXhwdmRzLmNsaXBzLmlnd3d3LUMzLmRhc2hfbG5faGVhYWNfdmJyM19hdWRpbyIsInZpZGVvX2lkIjpudWxsLCJvaWxfdXJsZ2VuX2FwcF9pZCI6OTM2NjE5NzQzMzkyNDU5LCJjbGllbnRfbmFtZSI6ImlnIiwieHB2X2Fzc2V0X2lkIjoxODk1MzYwNjIxMjgwMTU3LCJhc3NldF9hZ2VfZGF5cyI6NDQ5LCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6MTIsImJpdHJhdGUiOjY2MzUzLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&_nc_gid=BBInXT23pApv1zdZ-PzS-g&_nc_ss=72a8c&_nc_zt=28&oh=00_AQB0OhIS1rFBTFetuvbM_LoDuQW7JjYOcdeP7EsmdyuBtg&oe=6A699E71',
  'alt': 'Video by Дарья | Обзоры с WILDBERRIES | женственность on May 04, 2025.'},
 {'id': '3678763451202845825',
  'type': 'Video',
  'shortCode': 'DMNl94xoryB',
  'caption': 'На видео продукты от @mixit_ru 🫶🏻\n\nИдеальная пудра для лица артикул Вб:👇🏼\n#ww114857 \n\n@daria_grogulenko больше обзоров у меня в профиле, подпишись, чтобы не пропустить🫶🏻\n#вб #распаковка #образ #стиль',
  'hashtags': ['ww114857', 'вб', 'распаковка', 'образ', 'стиль'],
  'mentions': ['mixit_ru', 'daria_grogulenko'],
  'url': 'https://www.instagram.com/p/DMNl94xoryB/',
  'commentsCount': 1,
  'firstComment': '',
  'latestComments': [],
  'dimensionsHeight': 1970,
  'dimensionsWidth': 1110,
  'displayUrl': 'https://instagram.frtm1-3.fna.fbcdn.net/v/t51.82787-15/519521757_18333163753200212_7435749003451520415_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=102&ig_cache_key=MzY3ODc2MzQ1MTIwMjg0NTgyNTE4MzMzMTYzNzUwMjAwMjEy.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjExMTAuc2RyLnZpZGVvX2RlZmF1bHRfY292ZXJfZnJhbWUuQzMifQ%3D%3D&_nc_ohc=zg4m6Lw3sFkQ7kNvwHO0Ghm&_nc_oc=AdpoicvIDJr6huF0E8UeBlyneyEFYHNa5FUXHaiu6COXAgYC5ogtaN5LRWbCUjQjols&_nc_zt=23&_nc_ht=instagram.frtm1-3.fna&_nc_gid=pLcOt6NGzMoQHE9rj3XgOg&_nc_ss=7ca8c&oh=00_AQCPxmBszHZ1DdTe1hHpus9q3IsPgiJvSwBQwBKQRzHyDQ&oe=6A6D86C4',
  'images': [],
  'videoUrl': 'https://instagram.frtm1-2.fna.fbcdn.net/o1/v/t2/f2/m86/AQOAwYoib6TFuWgOg9CWaNx7IDG1ZcogoL7NsCzv3q4AZ6-X26_tLtXSbOXEDh28mid5erZ0ew8cmZOQC7HFODC47NvbPFf9b_rqBqY.mp4?_nc_cat=104&_nc_oc=Adrpan5ApXWVup6SCHJAeS3IEfxAgoInhtCtbMwZXDXSbhEFXkfOxuQY5Y4fBZGnw8o&_nc_sid=9ca052&_nc_ht=instagram.frtm1-2.fna.fbcdn.net&_nc_ohc=aJMcHfH37VQQ7kNvwFkMkXP&efg=eyJ2ZW5jb2RlX3RhZyI6ImlnLXhwdmRzLmNsaXBzLmlnd3d3LUMzLmRhc2hfYmFzZWxpbmVfM192MSIsInZpZGVvX2lkIjpudWxsLCJvaWxfdXJsZ2VuX2FwcF9pZCI6OTM2NjE5NzQzMzkyNDU5LCJjbGllbnRfbmFtZSI6ImlnIiwieHB2X2Fzc2V0X2lkIjo0MzYzMTc4OTAzOTA5NjY4LCJhc3NldF9hZ2VfZGF5cyI6Mzc1LCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6MTAsImJpdHJhdGUiOjIyNzEwNCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&_nc_gid=pLcOt6NGzMoQHE9rj3XgOg&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQDqAUrjjFRJY2VFbL72kEtlByJvpKQCSxo-4G46Foap2A&oe=6A69A53D',
  'likesCount': 7,
  'videoViewCount': 584,
  'timestamp': '2025-07-17T14:33:40.000Z',
  'childPosts': [],
  'locationName': 'Москва • Moscow',
  'locationId': 108889350634961,
  'ownerFullName': 'Дарья | Обзоры с WILDBERRIES | женственность',
  'ownerUsername': 'daria_grogulenko',
  'ownerId': '6006968211',
  'productType': 'clips',
  'paidPartnership': False,
  'taggedUsers': [{'full_name': 'MIXIT',
    'id': '1266587057',
    'is_verified': True,
    'profile_pic_url': 'https://scontent.cdninstagram.com/v/t51.2885-19/488802286_984395557131909_5715933892252572109_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=1&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=gNcIwPlTvIcQ7kNvwFPT5kk&_nc_oc=AdrQRkUYqwfWNU-apiuIk9WVAuGBySlUhisd9wWgrUVeyKa3vuw1pge--I5QnHSsuWk&_nc_zt=24&_nc_ht=scontent.cdninstagram.com&_nc_ss=7ca8c&oh=00_AQDvE3l2A8tvgKZaSMaU3-05FQ9veOMp2gQ9UCYSmIN8VA&oe=6A6DAAB9',
    'username': 'mixit_ru'}],
  'isCommentsDisabled': False,
  'inputUrl': 'https://www.instagram.com/daria_grogulenko/',
  'originalHeight': 640,
  'originalWidth': 360,

Перерсобираю данные в дикт, где ключ - имя блогера

In [45]:
result = {}

for username, posts in bloggers.items():
    first = posts[0]

    result[username] = {
        "username": username,
        "name": first.get("ownerFullName"),
        "posts": []
    }

    for p in posts:
        result[username]["posts"].append({
            "caption": p.get("caption"),
            "likes": p.get("likesCount"),
            "comments": p.get("commentsCount"),
            "image_url": p.get("displayUrl"),
            "video_url": p.get("videoUrl"),
            "timestamp": p.get("timestamp"),
            "hashtags": p.get("hashtags", []),
            "mentions": p.get("mentions", [])
        })

In [50]:
usernames = list(bloggers.keys())

print(len(usernames))
print(usernames[:10])

25
['daria_grogulenko', 'apple', 'v.m.beauty_blog', 'armlilitka', 'nike', 'jd_cosm', 'krrazalia', 'nikefootball', 'juliar_r', 'dddinaaaaaa']

Вызываю второй актор, собирающий профили

In [51]:
profile_input = {
    "usernames": usernames
}

In [52]:
PROFILE_ACTOR_ID = "dSCLg0C3YEZ83HzYX"
run_profile = client.actor(PROFILE_ACTOR_ID).call(
    run_input=profile_input
)

[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> Status: RUNNING, Message:
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:42.589Z ACTOR: Pulling container image of build rFWl2zI8F9JwqktLs from registry.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:42.591Z ACTOR: Creating container.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:42.628Z ACTOR: Starting container.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:42.628Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:43.206Z INFO  System info {"apifyVersion":"3.6.0","apifyClientVersion":"2.22.2","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v24.18.0"}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:43.334Z INFO  [Status message]: Starting the scraper with 24 direct URL(s)
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:43.541Z INFO  CheerioCrawler: Starting the crawler.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.248Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.248Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"tAOM61TdQAH25Vr","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=juliar_r","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.774Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> Status: RUNNING, Message: Starting the crawler.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.775Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"BjFmk0UqahrsSfu","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=apple","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.858Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.859Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"0wGePpgqRvz1dNI","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=jd_cosm","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.915Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.916Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"9t96COMJwX1WtwS","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=kristi_naxodka","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.951Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:44.951Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"TYiOJU8H3g0EcFq","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=anetboss_","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.022Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.022Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"SSG2T0QHuVXbnXv","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=daria_grogulenko","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.094Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.095Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"k48wNIASpVMjXiZ","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=aida.mixx","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.393Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.393Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"4R9w00jAy1WpmjE","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=krrazalia","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.403Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.403Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"ca5pFdorXbG6eHP","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=llaurraiiam","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.456Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.457Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"sFdrzX6DTv3lVKK","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=nike","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.485Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:45.485Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"bEve8DOMVZXqv1N","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=dddinaaaaaa","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:46.146Z INFO  web_profile_info returned HTTP 400, using route definition and details by id instead {"username":"yunglolaa"}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:46.810Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:46.810Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"liCdC3ACDioaaEc","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=armlilitka","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:47.670Z INFO  Resolved profile ID from route definition {"username":"yunglolaa","profileId":"5769346152"}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:48.822Z INFO  web_profile_info returned HTTP 400, using route definition and details by id instead {"username":"bazhenova.studio"}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:50.385Z INFO  web_profile_info returned HTTP 400, using route definition and details by id instead {"username":"ninooochka2.0"}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:50.512Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:50.513Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"xQMn2QwZgkdBagp","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=bazhenova_alenaa","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:51.019Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:51.020Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"4R9w00jAy1WpmjE","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=krrazalia","retryCount":2}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:52.244Z INFO  Resolved profile ID from route definition {"username":"bazhenova.studio","profileId":"42331410513"}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> Status: RUNNING, Message: Crawled 17/24 pages, 0 failed requests, desired concurrency 14.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:52.959Z INFO  Resolved profile ID from route definition {"username":"ninooochka2.0","profileId":"54481107697"}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:57.125Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. The proxy server rejected the request with status code 590 (UPSTREAM504)
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> Status: RUNNING, Message: Crawled 23/24 pages, 0 failed requests, desired concurrency 14.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:45:57.126Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"cVpQdfUqPccT9rm","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=_kate_bruni","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:46:15.451Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. request timed out after 30 seconds. {"id":"zyWofuv10LUz9nu","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=zari.ishikhovaa","retryCount":1}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:46:21.036Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:46:21.177Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":24,"requestsFailed":0,"retryHistogram":[9,14,1],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":3475,"requestsFinishedPerMinute":38,"requestsFailedPerMinute":0,"requestTotalDurationMillis":83393,"requestsTotal":24,"crawlerRuntimeMillis":37807}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:46:21.178Z INFO  CheerioCrawler: Finished! Total 24 requests: 24 succeeded, 0 failed. {"terminal":true}
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> 2026-07-27T21:46:21.178Z INFO  [Status message]: Scraper finished
[apify.instagram-profile-scraper runId:pmPaNifaEs8GjUzXl] -> Status: SUCCEEDED, Message: Scraper finished

In [53]:
profile_items = list(
    client.dataset(
        run_profile.default_dataset_id
    ).iterate_items()
)

print(len(profile_items))

24

In [54]:
pprint(profile_items[0])

{'biography': '🛍️ знаю где и как купить выгодно\n'
              '🐾 хозяйка 14 спасенышей 🐶🐱\n'
              '🌎🏡 с любовью к путешествиям и загородной жизни \n'
              '✨Тут все соц.сети ⬇️',
 'businessCategoryName': 'Blogger',
 'externalUrl': 'https://t.me/vmbeauty_blog1',
 'externalUrlShimmed': 'https://l.instagram.com/?u=https%3A%2F%2Ft.me%2Fvmbeauty_blog1&e=AUBsC61Rb3zH8sioOrQzHZOmwNF-xpU9mIwOwg3qd66UAeKNpboUNhuL7poCalwm9TUGIztzdGZ1mrVi6t31im85aeqV_vXl',
 'externalUrls': [{'link_type': 'external',
                   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Ft.me%2Fvmbeauty_blog1&e=AUBOuUpTLa_2NDj49oaB6jZ0BWzHuKt8ET_2N3YDbjJrGwqcMcDx_uN7wJ4IJjwQoAYDuOpMZAouDzqpmE8ckZaKJVGxvsb3',
                   'title': 'ТГ КАНАЛ 🤎',
                   'url': 'https://t.me/vmbeauty_blog1'},
                  {'link_type': 'external',
                   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Fmax.ru%2Fvmbeautyblog&e=AUBTosyrlB-pZVfun0-j_QY9MK5G2SjxC3qpPPcDsNhYL6ZyGPaByGW4o7l6C-pXoZGlFORyoaPbt2E_pd31ayfHc9S99liU',
                   'title': 'Я в MAX 📲',
                   'url': 'https://max.ru/vmbeautyblog'},
                  {'link_type': 'external',
                   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Fwww.tiktok.com%2F%40vmbeauty_blog%3F_t%3DZS-8xJWVQxqQfX%26_r%3D1&e=AUBdEEaPl0jr_vXo8IVmyRcwQUOLsmUck2RviaLjpaFLonuKBc_z2FwCT8kMLuBxJ4wD6s3A84sfD89CXfJVh9or0xgC5Vyr',
                   'title': 'Тик ток 💛',
                   'url': 'https://www.tiktok.com/@vmbeauty_blog?_t=ZS-8xJWVQxqQfX&_r=1'},
                  {'link_type': 'external',
                   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Fvk.com%2Fvmbeautyblog&e=AUB9e-GB-83PZhtizLEJRdr3GXNqXX3Iz-R8OE8Bxs1ZKekZJm7ciJ56F_rYzB31nJszgy5wETpbBuStFKKEByhLGMf9_28G',
                   'title': 'ВКонтакте сообщество 💗',
                   'url': 'https://vk.com/vmbeautyblog'},
                  {'link_type': 'external',
                   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Ft.me%2Flapkivdome&e=AUD_liJWXvgkt64Nx5F9Evao3A-2YaTbbH16Q-NTH7qrFehNxQwOu9EgMc5qpWUpbXjuuLPErBSxiVqYPGXIQtCxsf7oo8wC',
                   'title': 'ТГ КАНАЛ (о ремонте, доме) ♥️',
                   'url': 'https://t.me/lapkivdome'}],
 'fbid': '17841438240298516',
 'followersCount': 205852,
 'followsCount': 308,
 'fullName': 'Лера 🤎Тула-Москва Находки | Дом | Обзоры | Стиль | UGC',
 'highlightReelCount': 60,
 'id': '38308130676',
 'igtvVideoCount': 1,
 'inputUrl': 'https://www.instagram.com/v.m.beauty_blog',
 'isBusinessAccount': False,
 'joinedRecently': False,
 'latestIgtvVideos': [{'alt': None,
                       'caption': 'Хоть это видео было сделано почти год назад '
                                  'мне на день рождения от моих старушек 😂❤️, '
                                  'но тут самые яркие воспоминания \n'
                                  'Хочу, чтобы это видео было тут❤️\n'
                                  'Пусть и встречаемся мы не часто, но если '
                                  'встречаемся, то боятся все 😂❤️\n'
                                  '@sanchio_blue  @linettaaa__  и я😂\n'
                                  'в главных ролях 🥰',
                       'childPosts': [],
                       'commentsCount': 21,
                       'commentsDisabled': False,
                       'dimensionsHeight': 1333,
                       'dimensionsWidth': 750,
                       'displayUrl': 'https://scontent-nrt1-2.cdninstagram.com/v/t51.71878-15/642241658_1595845661693437_6555738171745138236_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-nrt1-2.cdninstagram.com&_nc_cat=101&_nc_oc=Q6cZ2gHo6RwkHxKz9hcUO2dAMl593XpPpZsrZcb1vUooRpBVLqAltXm8aEHX_umy9cfes6U&_nc_ohc=7kMCev30fjEQ7kNvwFEcku0&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AQBi_a31NorHXIUpeBpakfeS-lxE6OcBHLYQutKt9YlyaA&oe=6A6DB808&_nc_sid=8b3546',
                       'firstComment': '',
                       'hashtags': [],
                       'id': '2506184928365592829',
                       'images': [],
                       'isCommentsDisabled': False,
                       'latestComments': [],
                       'likesCount': 123,
                       'mentions': ['sanchio_blue', 'linettaaa__'],
                       'ownerId': '38308130676',
                       'ownerUsername': 'v.m.beauty_blog',
                       'productType': 'igtv',
                       'shortCode': 'CLHwen8q0D9',
                       'timestamp': '2021-02-10T18:13:34.000Z',
                       'title': 'HB Valera 🎉❤️',
                       'type': 'Video',
                       'url': 'https://www.instagram.com/p/CLHwen8q0D9/',
                       'videoDuration': 251.2,
                       'videoUrl': 'https://scontent-nrt6-1.cdninstagram.com/o1/v/t16/f2/m84/AQMY4LI0JCuWn35ROXr7Wavcn0SoIq3hbqQkrF4hBg7IkkX7pa1xDkvwyxLNrU1zUq6V8Rm-TRqRVDSXG4rI11HWIg1LEyUSpQ67JCA.mp4?_nc_cat=100&_nc_sid=5e9851&_nc_ht=scontent-nrt6-1.cdninstagram.com&_nc_ohc=Z2aYdmDdeowQ7kNvwHznzb8&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uSUdUVi5DMy43MjAuZGFzaF9iYXNlbGluZV8xX3YxIiwieHB2X2Fzc2V0X2lkIjoxMDA4NzQ5ODQ3MDY5NjkxLCJhc3NldF9hZ2VfZGF5cyI6MTk5MywidmlfdXNlY2FzZV9pZCI6MTAxNDUsImR1cmF0aW9uX3MiOjI1MSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=ca7bff6c6a043cd&_nc_vs=HBksFQIYTGlnX2JhY2tmaWxsX3RpbWVsaW5lX3ZvZC81MTRDOTgzQTUxNzY5RTU3OUI1ODcxNDI0NTUwQzg4Ql92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HRzE3OHhidC02VzhfMzBDQU90Qkh4Z05TQ1Y5YnBrd0FBQUYVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAm9o_qhPzcygMVAigCQzMsF0BvZmZmZmZmGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHXsB2XCngEA&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&_nc_zt=28&_nc_ss=7a3ba&oh=00_AQCOmB21Ua3WhxJQIW6SPsvgmLSjKAeTyshjxJOYkV7N4A&oe=6A69BF98',
                       'videoViewCount': 722}],
 'latestPosts': [{'alt': None,
                  'caption': 'Это не генетика и не «повезло». \n'
                             'Это постоянная работа над собой, полезные '
                             'привычки, спорт, питание и всё это обязательно в '
                             'комплексе с Голдлайн плюс ☀️\n'
                             '\n'
                             '#голдлайнплюс #голдлайн #худеем #зож',
                  'childPosts': [],
                  'commentsCount': 54,
                  'dimensionsHeight': 1136,
                  'dimensionsWidth': 640,
                  'displayUrl': 'https://scontent-nrt1-2.cdninstagram.com/v/t51.71878-15/751591569_2112547436325343_2774782023586357929_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-nrt1-2.cdninstagram.com&_nc_cat=107&_nc_oc=Q6cZ2gHo6RwkHxKz9hcUO2dAMl593XpPpZsrZcb1vUooRpBVLqAltXm8aEHX_umy9cfes6U&_nc_ohc=Q1tQRulX9XQQ7kNvwHg1eiM&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AQBhkehLmHOVJzBzII71zqQeS7QDxhyBudaY2yFNo7qOXQ&oe=6A6DBE30&_nc_sid=8b3546',
                  'hashtags': ['голдлайнплюс', 'голдлайн', 'худеем', 'зож'],
                  'id': '3946855556955982871',
                  'images': [],
                  'isCommentsDisabled': False,
                  'isPinned': True,
                  'likesCount': 40,
                  'mentions': [],
                  'ownerId': '38308130676',
                  'ownerUsername': 'v.m.beauty_blog',
                  'productType': 'clips',
                  'shortCode': 'DbGDDe8I0wX',
                  'timestamp': '2026-07-22T12:05:22.000Z',
                  'type': 'Video',
                  'url': 'https://www.instagram.com/p/DbGDDe8I0wX/',
                  'videoUrl': 'https://scontent-nrt6-1.cdninstagram.com/o1/v/t2/f2/m86/AQNeCo9yXIbCtXGIy235Ey5lVflHSHt0iFF-5AsMf_0CwXnGee1JqPhe8KP8AVCjzz4bx0ctHeYFhYQ63Med6J-w85zzUJvtqdVgRb8.mp4?_nc_cat=105&_nc_sid=5e9851&_nc_ht=scontent-nrt6-1.cdninstagram.com&_nc_ohc=bCCd5l6jgQ4Q7kNvwF2uT6c&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTY5MjY5ODI0MTk0NTgxMCwiYXNzZXRfYWdlX2RheXMiOjUsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjo1NiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=52e429d5de9129fb&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9DRTQ1MjRCMDhCNDc1RDUxNDQxNUY3NEI1NTlFMEM5MV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzcyNDE4RUJEMjUyQ0M2MTNCOERGOUQ0NTZEMTkwMDlCX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACakw-LWgOCBBhUCKAJDMywXQExIcrAgxJwYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&_nc_ss=7a3ba&_nc_zt=28&oh=00_AQDgZ2V-g2pn_uPgcJbbXdP0i7Mpupp3jzQSHxkAWw8Ruw&oe=6A69BA56',
                  'videoViewCount': None},
                 {'alt': None,
                  'caption': 'Девушки и их супер способности 😂\n'
                             'Умеем, согласны? 🤭\n'
                             '\n'
                             'Сейчас за лицом уход в летний период очень люблю '
                             'простой, не жирный, а самое главное - '
                             'освежающий! \n'
                             'Крем-лед и гель-лед с этим очень хорошо '
                             'справляются! \n'
                             'Эффект нового дива, правда! 😄\n'
                             'Устраняют отеки, крем хорошо увлажняет и '
                             'охлаждает, а гель отлично очищает кожу лица!\n'
                             '\n'
                             'А ещё, кстати, когда я была маленькая, очень '
                             'хорошо помню, что у мамы была маска-пленка и я '
                             'очень любила ее отдирать! Всегда прям ждала, '
                             'когда она ее будет делать 🥺\n'
                             'А теперь у меня у самой есть такая маска-пленка. '
                             'Не только хорошее средство для кожи, но ещё и '
                             'такое приятное воспоминание из детства 🧡\n'
                             'Ну а на макияж - румяна и тушь, что ещё оето',
                  'childPosts': [],
                  'commentsCount': 16,
                  'dimensionsHeight': 1916,
                  'dimensionsWidth': 1080,
                  'displayUrl': 'https://scontent-nrt6-1.cdninstagram.com/v/t51.82787-15/757596435_18106416368274677_8198901924056726917_n.jpg?stp=dst-jpg_e35_p1080x1080_sh2.08_tt6&_nc_ht=scontent-nrt6-1.cdninstagram.com&_nc_cat=105&_nc_oc=Q6cZ2gHo6RwkHxKz9hcUO2dAMl593XpPpZsrZcb1vUooRpBVLqAltXm8aEHX_umy9cfes6U&_nc_ohc=bOjBeBYh2FoQ7kNvwFCRzBC&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AQA9DqZEP_i7gQpSnWwrZlKBNIMFVEUiBhNa7Z5LRR8tsg&oe=6A6D912F&_nc_sid=8b3546',
                  'hashtags': [],
                  'id': '3950580802678450079',
                  'images': [],
                  'isCommentsDisabled': False,
                  'likesCount': 573,
                  'locationId': '221674386',
                  'locationName': 'Tula, Russia',
                  'mentions': [],
                  'ownerId': '38308130676',
                  'ownerUsername': 'v.m.beauty_blog',
                  'productType': 'clips',
                  'shortCode': 'DbTSE8YIGef',
                  'timestamp': '2026-07-27T15:26:59.000Z',
                  'type': 'Video',
                  'url': 'https://www.instagram.com/p/DbTSE8YIGef/',
                  'videoUrl': 'https://scontent-nrt1-2.cdninstagram.com/o1/v/t2/f2/m86/AQOdhA5Ascr9vFdPdtsM6zl7CJKxRk-rVwYGFM-_bkTBhU1z4b1sU6m3xgXONuUMxf2QO3KMP1ZD5GZN2z2A7WT2jncC6o5Pa1fRYbs.mp4?_nc_cat=102&_nc_sid=5e9851&_nc_ht=scontent-nrt1-2.cdninstagram.com&_nc_ohc=RWdonIFTv04Q7kNvwHs5-Ca&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTU5ODY4Nzg0MTk3MjQzNywiYXNzZXRfYWdlX2RheXMiOjAsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoxOCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=be7bb4113946b481&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC80NzQxQkE5ODA4MTIzRkRBRkE3OUJDQTE1REUwOUM4M192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0I5NDA2QzZFNEE4NTBDODc4RUJCMEZGOTBGOTdGMkEzX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaqw-vO8P_WBRUCKAJDMywXQDKZmZmZmZoYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&_nc_ss=7a3ba&_nc_zt=28&oh=00_AQDV4BYnb1xRMYAzauM2lx7jsTdWiHXoWOdLTt2AIMKXjQ&oe=6A69C893',
                  'videoViewCount': None},
                 {'alt': None,
                  'caption': '',
                  'childPosts': [],
                  'commentsCount': 5,
                  'dimensionsHeight': 1333,
                  'dimensionsWidth': 750,
                  'displayUrl': 'https://scontent-nrt6-1.cdninstagram.com/v/t51.82787-15/756609821_18106327826274677_6655577064149423636_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-nrt6-1.cdninstagram.com&_nc_cat=105&_nc_oc=Q6cZ2gHo6RwkHxKz9hcUO2dAMl593XpPpZsrZcb1vUooRpBVLqAltXm8aEHX_umy9cfes6U&_nc_ohc=DPPaN2XXdJsQ7kNvwG2RHL5&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AQDjaSkHZMmotjIV4DyKa30OvN0LzE4Qa24L92FTTVVsDQ&oe=6A6DAD9E&_nc_sid=8b3546',
                  'hashtags': [],
                  'id': '3950068002910703242',
                  'images': [],
                  'isCommentsDisabled': False,
                  'likesCount': 12,
                  'locationId': '108889350634961',
                  'locationName': 'Москва • Moscow',
                  'mentions': [],
                  'ownerId': '38308130676',
                  'ownerUsername': 'v.m.beauty_blog',
                  'productType': 'clips',
                  'shortCode': 'DbRdeuYIQ6K',
                  'timestamp': '2026-07-26T22:27:43.000Z',
                  'type': 'Video',
                  'url': 'https://www.instagram.com/p/DbRdeuYIQ6K/',
                  'videoUrl': 'https://scontent-nrt1-2.cdninstagram.com/o1/v/t2/f2/m86/AQMb2W1B9UbIB8OGyxnj29-KjgAUnjorcaETDaEEHEpl0W7Tep-3XOcpcYZUMUwx03Uj7Wq4RAAdTWTYSy3S4EYd25m4fcoNPASW-A0.mp4?_nc_cat=102&_nc_sid=5e9851&_nc_ht=scontent-nrt1-2.cdninstagram.com&_nc_ohc=6UBTSZvY7mEQ7kNvwFFZPPJ&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTYzMDc1MjE4ODQ0NDMyMCwiYXNzZXRfYWdlX2RheXMiOjAsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoxNiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=e7acd6ce6c3a2dd4&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8yQjQzQzg3OTdEQUZEOTI5NEQ5QzI0QzU3MkVDMUI5Ql92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzU4NERFQTJGQUQ2MkY0RDFFOTNGOTBGNDkxMzVBQTlCX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbAusXOosrlBRUCKAJDMywXQDC7peNT988YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&_nc_ss=7a3ba&_nc_zt=28&oh=00_AQDfNnfj1PWor48vNbD-tG8wsJqYknqo5FX_LwxwS-FCaQ&oe=6A699B87',
                  'videoViewCount': None},
                 {'alt': None,
                  'caption': 'Это законно вообще? 😂\n'
                             '\n'
                             'Пенка, кстати, с вб ✅\n'
                             '\n'
                             'арт. #270127197',
                  'childPosts': [],
                  'commentsCount': 4,
                  'dimensionsHeight': 1136,
                  'dimensionsWidth': 640,
                  'displayUrl': 'https://scontent-nrt1-2.cdninstagram.com/v/t51.71878-15/755331928_1722316015480468_4046414775336764664_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-nrt1-2.cdninstagram.com&_nc_cat=104&_nc_oc=Q6cZ2gHo6RwkHxKz9hcUO2dAMl593XpPpZsrZcb1vUooRpBVLqAltXm8aEHX_umy9cfes6U&_nc_ohc=ONku63h0O-oQ7kNvwGcWNky&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AQDL5seCgBaQJ6HcjvvO_jitlWwP-ua0UPQxRK0jYEzWIA&oe=6A6DB236&_nc_sid=8b3546',
                  'hashtags': ['270127197'],
                  'id': '3950006314119458994',
                  'images': [],
                  'isCommentsDisabled': False,
                  'likesCount': 10,
                  'locationId': '108889350634961',
                  'locationName': 'Москва • Moscow',
                  'mentions': [],
                  'musicInfo': {'artist_name': 'Katherine Cordova',
                                'audio_id': '1002640841152539',
                                'should_mute_audio': False,
                                'should_mute_audio_reason': '',
                                'song_name': 'Succession Main Title Theme '
                                             '(piano arrangement)',
                                'uses_original_audio': False},
                  'ownerId': '38308130676',
                  'ownerUsername': 'v.m.beauty_blog',
                  'productType': 'clips',
                  'shortCode': 'DbRPdCNo_Cy',
                  'timestamp': '2026-07-26T20:25:05.000Z',
                  'type': 'Video',
                  'url': 'https://www.instagram.com/p/DbRPdCNo_Cy/',
                  'videoUrl': 'https://scontent-nrt1-1.cdninstagram.com/o1/v/t2/f2/m86/AQNtUGcgqF5ChVhzWonhFdLAvfBXAwtZkg5TUKVKafkFT7ED67Q80SFQVmLyKjd0DdtnvU55AIzXEi42OuiRJXDAp2tWX_IDf1tBM7w.mp4?_nc_cat=109&_nc_sid=5e9851&_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_ohc=yQk9dk8jECUQ7kNvwFOnwkk&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6OTAxMjM3NzE1ODE4MDU0LCJhc3NldF9hZ2VfZGF5cyI6MSwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjgsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=b829489cda824f23&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8wODQ3RkMxNDBCQzk1RTVERTQ3N0YxMzAzOEYxMDVCM192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzhCNDk3Mzc1NEZCM0I4RDU2NjAxREVBNTdFRjBFQzg5X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaM2cae-OqZAxUCKAJDMywXQCEAAAAAAAAYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&_nc_ss=7a3ba&_nc_zt=28&oh=00_AQC5-eUz762EJmLhXleEeuzNh3ahVBmGr9LuPvtAYMyJ8Q&oe=6A69BE16',
                  'videoViewCount': None},
                 {'alt': None,
                  'caption': 'СДЕЛАЛА ЧЕХОЛ СО СВОИМИ ПУШИСТЫМИ 🥺💔😍\n'
                             '\n'
                             'Брала всю эту красоту у @caseplace.ru 🫰🏻\n'
                             '\n'
                             'артикулы с озон👇🏻\n'
                             'бабочки #2877236187\n'
                             'цветы белый #4206858581\n'
                             'цветы прозрачный #2834084217\n'
                             'бантики #2830235208\n'
                             'леопард 3085661322\n'
                             'со своим фото #3164131468',
                  'childPosts': [],
                  'commentsCount': 11,
                  'dimensionsHeight': 1136,
                  'dimensionsWidth': 640,
                  'displayUrl': 'https://scontent-nrt1-2.cdninstagram.com/v/t51.71878-15/756046283_837956825937974_1870175729914348373_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-nrt1-2.cdninstagram.com&_nc_cat=102&_nc_oc=Q6cZ2gHo6RwkHxKz9hcUO2dAMl593XpPpZsrZcb1vUooRpBVLqAltXm8aEHX_umy9cfes6U&_nc_ohc=bnK8OsIBVrYQ7kNvwFBibA4&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AQAO7uvdrzqLjNY0WDkOKBgsx4u-BP6DUY4dOsT6J5RoVw&oe=6A6DA749&_nc_sid=8b3546',
                  'hashtags': ['2877236187',
                               '4206858581',
                               '2834084217',
                               '2830235208',
                               '3164131468'],
                  'id': '3949213351000887327',
                  'images': [],
                  'isCommentsDisabled': False,
                  'likesCount': 11,
                  'locationId': '108889350634961',
                  'locationName': 'Москва • Moscow',
                  'mentions': ['caseplace.ru'],
                  'ownerId': '38308130676',

Объединяю данные профилей и постов

In [56]:
profiles = {}

for profile in profile_items:
    username = profile.get("username")

    profiles[username] = {
        "full_name": profile.get("fullName"),
        "bio": profile.get("biography"),

        "followers": profile.get("followersCount"),
        "following": profile.get("followsCount"),
        "posts_count": profile.get("postsCount"),

        "category": profile.get("businessCategoryName"),

        "external_urls": profile.get("externalUrls"),

        "profile_image": profile.get("profilePicUrlHD")
    }

In [57]:
profiles["v.m.beauty_blog"]

{'full_name': 'Лера 🤎Тула-Москва Находки | Дом | Обзоры | Стиль | UGC',
 'bio': '🛍️ знаю где и как купить выгодно\n🐾 хозяйка 14 спасенышей 🐶🐱\n🌎🏡 с любовью к путешествиям и загородной жизни \n✨Тут все соц.сети ⬇️',
 'followers': 205852,
 'following': 308,
 'posts_count': 1290,
 'category': 'Blogger',
 'external_urls': [{'title': 'ТГ КАНАЛ 🤎',
   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Ft.me%2Fvmbeauty_blog1&e=AUBOuUpTLa_2NDj49oaB6jZ0BWzHuKt8ET_2N3YDbjJrGwqcMcDx_uN7wJ4IJjwQoAYDuOpMZAouDzqpmE8ckZaKJVGxvsb3',
   'url': 'https://t.me/vmbeauty_blog1',
   'link_type': 'external'},
  {'title': 'Я в MAX 📲',
   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Fmax.ru%2Fvmbeautyblog&e=AUBTosyrlB-pZVfun0-j_QY9MK5G2SjxC3qpPPcDsNhYL6ZyGPaByGW4o7l6C-pXoZGlFORyoaPbt2E_pd31ayfHc9S99liU',
   'url': 'https://max.ru/vmbeautyblog',
   'link_type': 'external'},
  {'title': 'Тик ток 💛',
   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Fwww.tiktok.com%2F%40vmbeauty_blog%3F_t%3DZS-8xJWVQxqQfX%26_r%3D1&e=AUBdEEaPl0jr_vXo8IVmyRcwQUOLsmUck2RviaLjpaFLonuKBc_z2FwCT8kMLuBxJ4wD6s3A84sfD89CXfJVh9or0xgC5Vyr',
   'url': 'https://www.tiktok.com/@vmbeauty_blog?_t=ZS-8xJWVQxqQfX&_r=1',
   'link_type': 'external'},
  {'title': 'ВКонтакте сообщество 💗',
   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Fvk.com%2Fvmbeautyblog&e=AUB9e-GB-83PZhtizLEJRdr3GXNqXX3Iz-R8OE8Bxs1ZKekZJm7ciJ56F_rYzB31nJszgy5wETpbBuStFKKEByhLGMf9_28G',
   'url': 'https://vk.com/vmbeautyblog',
   'link_type': 'external'},
  {'title': 'ТГ КАНАЛ (о ремонте, доме) ♥️',
   'lynx_url': 'https://l.instagram.com/?u=https%3A%2F%2Ft.me%2Flapkivdome&e=AUD_liJWXvgkt64Nx5F9Evao3A-2YaTbbH16Q-NTH7qrFehNxQwOu9EgMc5qpWUpbXjuuLPErBSxiVqYPGXIQtCxsf7oo8wC',
   'url': 'https://t.me/lapkivdome',
   'link_type': 'external'}],
 'profile_image': 'https://scontent-nrt6-1.cdninstagram.com/v/t51.2885-19/497061688_18060086102274677_1773531388999466215_n.jpg?stp=dst-jpg_s320x320_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLmRqYW5nby4xMDgwLmMyIn0&_nc_ht=scontent-nrt6-1.cdninstagram.com&_nc_cat=105&_nc_oc=Q6cZ2gHo6RwkHxKz9hcUO2dAMl593XpPpZsrZcb1vUooRpBVLqAltXm8aEHX_umy9cfes6U&_nc_ohc=KnlzL8YfOw0Q7kNvwGtH2oY&_nc_gid=5R8zusrMaQM8KM_KuVxriQ&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AQDHcVF5IsoL2v9RC0-roUK0H7r-nkfkAHQvs7lVvZ05lQ&oe=6A6DBCB5&_nc_sid=8b3546'}

In [58]:
for username, blogger in result.items():

    profile = profiles.get(username)

    if profile:
        blogger.update(profile)

На всякий случай нормализую данные ников, привожу к нижнему регистру

In [59]:
def normalize_username(username):
    return username.lower().replace("@", "").strip()


profiles = {
    normalize_username(k): v
    for k,v in profiles.items()
}


for username, blogger in result.items():

    key = normalize_username(username)

    if key in profiles:
        blogger.update(profiles[key])

In [60]:
print(result["v.m.beauty_blog"])

{'username': 'v.m.beauty_blog', 'name': 'Лера 🤎Тула-Москва Находки | Дом | Обзоры | Стиль | UGC', 'posts': [{'caption': '', 'likes': -1, 'comments': 5, 'image_url': 'https://instagram.fqro3-1.fna.fbcdn.net/v/t51.82787-15/756609821_18106327826274677_6655577064149423636_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=102&ig_cache_key=Mzk1MDA2ODAwMjkxMDcwMzI0MjE4MTA2MzI3ODIzMjc0Njc3.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjcyMC5zZHIudmlkZW9fZGVmYXVsdF9jb3Zlcl9mcmFtZS5DMyJ9&_nc_ohc=CSdQkZKsOvQQ7kNvwHzB54B&_nc_oc=AdrD181802vtzBFhmHBnzGDA1WqZqGEKkyqzS7mIZHqSh26XstJiqcgo68s1fgV2p1rERyqq1a1f9LdTFtmX8MNR&_nc_zt=23&_nc_ht=instagram.fqro3-1.fna&_nc_gid=b06vwj8cE6GisMCzy23c1g&_nc_ss=7b60f&oh=00_AQAZMN14oYxd0MPeaHzR3SFEleeHmRFaKGBzvGpyf5QYVQ&oe=6A6DAD9E', 'video_url': 'https://instagram.fqro3-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQMb2W1B9UbIB8OGyxnj29-KjgAUnjorcaETDaEEHEpl0W7Tep-3XOcpcYZUMUwx03Uj7Wq4RAAdTWTYSy3S4EYd25m4fcoNPASW-A0.mp4?_nc_cat=102&_nc_oc=AdrYeqQ9gqclfmuo7YzOoA57LUpCLyOxezQpYlIXvpxYiOSrRQr0NsGTHcYrTWWB3Jp0rQh2P11rSBob1Dd0TC1n&_nc_sid=5e9851&_nc_ht=instagram.fqro3-1.fna.fbcdn.net&_nc_ohc=6UBTSZvY7mEQ7kNvwEhrsKz&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTYzMDc1MjE4ODQ0NDMyMCwiYXNzZXRfYWdlX2RheXMiOjAsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoxNiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=e7acd6ce6c3a2dd4&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8yQjQzQzg3OTdEQUZEOTI5NEQ5QzI0QzU3MkVDMUI5Ql92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzU4NERFQTJGQUQ2MkY0RDFFOTNGOTBGNDkxMzVBQTlCX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbAusXOosrlBRUCKAJDMywXQDC7peNT988YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=b06vwj8cE6GisMCzy23c1g&_nc_ss=7b60f&_nc_zt=28&oh=00_AQDoXAYN8jenq6UJwMc6gNTP0Nvgk3GXoK9XG-Lu687VCg&oe=6A699B87', 'timestamp': '2026-07-26T22:27:43.000Z', 'hashtags': [], 'mentions': []}, {'caption': 'СДЕЛАЛА ЧЕХОЛ СО СВОИМИ ПУШИСТЫМИ 🥺💔😍\n\nБрала всю эту красоту у @caseplace.ru 🫰🏻\n\nартикулы с озон👇🏻\nбабочки #2877236187\nцветы белый #4206858581\nцветы прозрачный #2834084217\nбантики #2830235208\nлеопард 3085661322\nсо своим фото #3164131468', 'likes': -1, 'comments': 11, 'image_url': 'https://scontent-lhr6-1.cdninstagram.com/v/t51.71878-15/756046283_837956825937974_1870175729914348373_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=109&ig_cache_key=Mzk0OTIxMzM1MTAwMDg4NzMyNw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjY0MC5zZHIudmlkZW9fbmZyYW1lX2NvdmVyX2ZyYW1lLkMzIn0%3D&_nc_ohc=orp4D4Px8tgQ7kNvwE-XOh0&_nc_oc=Adprcdm-MuyG4wq-oJk_LSfNK25qyjYbeKsiHZsOHBagQkqyW1yqum_4UgRXxddtF7dMkDucQML7nacW-JkhsMgq&_nc_zt=23&_nc_ht=scontent-lhr6-1.cdninstagram.com&_nc_gid=9mY_OBXwUYx63s4O2QeZIg&_nc_ss=7c689&oh=00_AQCg0SwdX5hqtNRgs8YjDSs3CsSpxHBy2MvGVqMZ3jrP_Q&oe=6A6DA749', 'video_url': 'https://scontent-lhr6-2.cdninstagram.com/o1/v/t2/f2/m86/AQNZ1pOHPVxdZZNnTdcg3gSz-Imt0HzGDPJ9iLG_bl14Zzrm5Zc2E3Gc5hzje6QgxPiIzbxQGvWS6GnJIx0ncqcceU6TYu2J4Y86Gog.mp4?_nc_cat=105&_nc_sid=5e9851&_nc_ht=scontent-lhr6-2.cdninstagram.com&_nc_ohc=zoubUKn8_RQQ7kNvwHWsu5Y&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTM1NDQ2OTI0NjkwMTY5OCwiYXNzZXRfYWdlX2RheXMiOjIsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjozMiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=fdb28e9fd9256fa&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8xNTRDMzE5RkQ2QzU3MjE2MDIxN0YzODMzQjRCQjA5QV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0NGNDk5RDMzMTFFNjlCOUQwNjU4MzgwNTM2OTVCQjg0X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaE95ClvvjnBBUCKAJDMywXQEAd0vGp--cYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=9mY_OBXwUYx63s4O2QeZIg&_nc_ss=7c689&_nc_zt=28&oh=00_AQCN2CYqROkPT6ofVHmEy5omPQvRPLyo04-3VYJkf9UO2g&oe=6A69BAC2', 'timestamp': '2026-07-25T18:17:44.000Z', 'hashtags': ['2877236187', '4206858581', '2834084217', '2830235208', '3164131468'], 'mentions': ['caseplace.ru']}, {'caption': 'ну какой наборчик нашей банде 🥹🥰🐈\n\nна вб #265834475', 'likes': -1, 'comments': 3, 'image_url': 'https://instagram.fyyc2-1.fna.fbcdn.net/v/t51.71878-15/753503245_3162207290639990_2286098570844474269_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=106&ig_cache_key=Mzk0Nzc5NDk0OTIxNjU2NjM2OQ%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjY0MC5zZHIudmlkZW9fbmZyYW1lX2NvdmVyX2ZyYW1lLkMzIn0%3D&_nc_ohc=f_pXr56QAsYQ7kNvwFY7RoJ&_nc_oc=Adrtaw-N1wOfECsw-LjhTkZiKsaSxWA83EGlqACmEDqfLJ2Qv6F_gOgtgvoyCU6F3UJj4igGpw1kKE89NwCBwRhP&_nc_zt=23&_nc_ht=instagram.fyyc2-1.fna&_nc_gid=jylz6N25iWX7kq7goRX2Ng&_nc_ss=72689&oh=00_AQAWQifelPL64zCLlthxDSruTbcrqWbkJwIBit0gJ8C2lQ&oe=6A6DAC37', 'video_url': 'https://instagram.fyyc2-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQPve9yDAxfNTW3bvdg0WEgPmFPLBJMX4rTDs7awXuGfjHS8bcoLqoq7cLIV_S-4onQjCwuX8186BGqsVN6jYaVZ7ZzObBv9pj9WRA8.mp4?_nc_cat=102&_nc_oc=Adophkm30Pk5WkszzyCFQp3rrrV1EqPJCpLgTu0-rtgZJF221seu5gf28d398ctki1w8TxahE7FVrtEg7yPTUcXH&_nc_sid=5e9851&_nc_ht=instagram.fyyc2-1.fna.fbcdn.net&_nc_ohc=ll5UFBugA80Q7kNvwEgqor_&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTUwNTgxODYzMDgyOTc5NCwiYXNzZXRfYWdlX2RheXMiOjQsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoxMCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=78818de7d76eb61d&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9FNzRGQTczQTgyNjRFNDk5RTdCOUNFRjFFRUM3QTY5NF92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzMyNDcxNjM3RUNDMDBCOTY0QjA2ODI4NzIzN0ZENTg0X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbE27GJl-KsBRUCKAJDMywXQCRmZmZmZmYYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=jylz6N25iWX7kq7goRX2Ng&_nc_ss=72689&_nc_zt=28&oh=00_AQCcYYSaG03gVmOcRoBN0i5aB1QJf5iVSu7jXK_9sipISA&oe=6A699E5B', 'timestamp': '2026-07-23T19:12:00.000Z', 'hashtags': ['265834475'], 'mentions': []}, {'caption': 'Какая 🧡🪴\n\nбромелия с вб #1241966360 от @greentown.online', 'likes': -1, 'comments': 4, 'image_url': 'https://instagram.fyyc6-1.fna.fbcdn.net/v/t51.71878-15/753267273_1046037711253268_6868032548544980806_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=instagram.fyyc6-1.fna.fbcdn.net&_nc_cat=108&_nc_oc=Q6cZ2gGB4JN0UT2xjr5U4oZdoUGCUoK8CVsUvEDoiHsqhmRGe6NiVFQjmbFc6VYUNVsJTOk&_nc_ohc=hz6SMlzS52wQ7kNvwGcdUIl&_nc_gid=glAkeoAhcA1DUtyd49oBKQ&edm=ADp7STQBAAAA&ccb=7-5&oh=00_AQB6Lj56Sh6B1JdveUrGa67gbq5pJTrorVe9t6c0X-cayQ&oe=6A6D8C0A&_nc_sid=c6f216', 'video_url': 'https://scontent-yyz1-1.cdninstagram.com/o1/v/t2/f2/m86/AQPE8nihk0SyCj5QItzw2zvTUm5fF75HzyIeXZ_AZZvdtZUzrv4YWLx5uzwL0pO-V28joNq-Vjr4np5xMXj8MM8DsrGD0MwGwaGGxmU.mp4?_nc_cat=102&_nc_sid=5e9851&_nc_ht=scontent-yyz1-1.cdninstagram.com&_nc_ohc=AyQM3YNICAoQ7kNvwHtFF7P&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6OTE5NjAzMDcwMzk3NTk3LCJhc3NldF9hZ2VfZGF5cyI6NSwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjcsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=bd7d7c593406dd13&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC82QzQ5MDVGOTMyNzVFOUREMTUzNDk0NDAxQkNGQTZCM192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0UyNDVGQjVEQ0ZGN0ZCNTJBRUM5MDQ5NDE4NUJGRDlBX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACa6ssPl-JeiAxUCKAJDMywXQB4hysCDEm8YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=NpiFDdaFRyQgxNG2cWgO5g&_nc_ss=72a8c&_nc_zt=28&oh=00_AQD3pQt3xn38_fovis1fsdEN9WlaSZoFvd2tpxV1HmJLVw&oe=6A69915F', 'timestamp': '2026-07-21T23:17:03.000Z', 'hashtags': ['1241966360'], 'mentions': ['greentown.online']}, {'caption': 'найти баночки для моего проблемного лица - та еще задача 🤪\nно тут все совпало 🥹🫶🏻 \nкремик от @aravia_professional @aravia_laboratories', 'likes': -1, 'comments': 6, 'image_url': 'https://scontent-lhr11-1.cdninstagram.com/v/t51.71878-15/755264101_1432211708746075_3398792344682853971_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=111&ig_cache_key=Mzk0Nzc2NDYyNDE4MDU1MzY4OQ%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjY0MC5zZHIudmlkZW9fbmZyYW1lX2NvdmVyX2ZyYW1lLkMzIn0%3D&_nc_ohc=YVpUTEqsf4cQ7kNvwEfwY6j&_nc_oc=AdqGHWC_WqCccY-K7lgE8ofhnk8lW1xOURGOT1N_Th1HMj1Ra_UdOtqJ-WlV9eUeHmA&_nc_zt=23&_nc_ht=scontent-lhr11-1.cdninstagram.com&_nc_gid=D6S1mGKPlYhwUL2DGOXcWw&_nc_ss=72a8c&oh=00_AQBYQZBmqtv6Ak-a8HxRWU9NysLNW9zu5CbW2uOvQ7OEaA&oe=6A6DB3B0', 'video_url': 'https://scontent-lhr6-1.cdninstagram.com/o1/v/t2/f2/m86/AQNWPPzOay1e-eFIprB-4sKAUgM8RtJnOsIxUGtxavpgTEMGakhw-8W1Y9BU9SnfMceL9WYJBlSiXDk9n1IkzXPuFGbl_hLCh3gsqYI.mp4?_nc_cat=103&_nc_sid=5e9851&_nc_ht=scontent-lhr6-1.cdninstagram.com&_nc_ohc=QxjOF7IACt0Q7kNvwGTLaaS&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MjUwMjc3OTE3MDE0OTE0OCwiYXNzZXRfYWdlX2RheXMiOjQsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoxNiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=278ae4b1b5315848&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC83QzQzOUY5NzkzNDBCNDBGNzRFMjg2OEQyQTE5NTdCQl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzJENEREQjFEOUIzMTc3NDI4QkFFMEQwMjVDM0JDOUE2X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACa4zJr29ZDyCBUCKAJDMywXQDAQ5WBBiTcYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=D6S1mGKPlYhwUL2DGOXcWw&_nc_ss=72a8c&_nc_zt=28&oh=00_AQCTXOAmqi9jx4r0WFQIUdskdjUN3rBq9GHQpjdofsMBIQ&oe=6A69BBCC', 'timestamp': '2026-07-23T18:13:01.000Z', 'hashtags': [], 'mentions': ['aravia_professional', 'aravia_laboratories']}, {'caption': 'А у вас как? 🫶🏻\n\nМой кондиционер с вб #342861625\nСкраб для тела #348267988', 'likes': -1, 'comments': 5, 'image_url': 'https://scontent-sea5-1.cdninstagram.com/v/t51.71878-15/755868040_2009783109641538_362440754165685246_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=110&ig_cache_key=Mzk0ODk2MDc5OTI0ODI2NDc5MQ%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjY0MC5zZHIudmlkZW9fZGVmYXVsdF9jb3Zlcl9mcmFtZS5DMyJ9&_nc_ohc=9dDj3g0IaT8Q7kNvwHENNSJ&_nc_oc=AdrCdC1WYX3S2lIL7pJOs0jTApEIR1Mf9ukazD0y2qPPVnDj5suy_YxeEsHDDZdHgcI&_nc_zt=23&_nc_ht=scontent-sea5-1.cdninstagram.com&_nc_gid=KZfGVmZ_4CuycVdpf2B0VQ&_nc_ss=72289&oh=00_AQBA9mwFxqsIcJsNN6nObo7bUTwc0rGgB0_CUDQ-UxwVfA&oe=6A6DB013', 'video_url': 'https://scontent-sea5-1.cdninstagram.com/o1/v/t2/f2/m86/AQMA-AcuE9kEwF_z9Luy322p6hzozfznjGU_beA7yijMcVcGfaQTY7C8G9HBwYs59O_y9u_OVLQO83loEPKFjzL94WSd6qS058Td0DE.mp4?_nc_cat=108&_nc_sid=5e9851&_nc_ht=scontent-sea5-1.cdninstagram.com&_nc_ohc=aw4JVJbyRfgQ7kNvwFAslN6&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTAwODc1NjYzODczMjI0NCwiYXNzZXRfYWdlX2RheXMiOjIsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjo3LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=252b7468057af99d&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC85OTQ2N0YzMTVBODJCRjQyNTM2Qjg2RUQzQTk2MERCN192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0YxNDQ0OUZERTlCMjU1QjQzREQ3OUE4Njg5RjcyOEExX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaov-7Rrt3KAxUCKAJDMywXQBwhysCDEm8YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=KZfGVmZ_4CuycVdpf2B0VQ&_nc_zt=28&_nc_ss=72289&oh=00_AQAd77Rxy3R0uwUXKo930LHmPLDP0l1lwR4EqRdLNTMm6g&oe=6A69A511', 'timestamp': '2026-07-25T09:47:44.000Z', 'hashtags': ['342861625', '348267988'], 'mentions': []}, {'caption': 'коробочка приятных баночек 🥹\nну люблю я все новое пробовать, благодаря этой красоте 🍏\n\n#glambox #коробкакрасоты #боксы', 'likes': -1, 'comments': 4, 'image_url': 'https://scontent-phx1-1.cdninstagram.com/v/t51.82787-15/752514763_18105635066274677_8355999796353866746_n.jpg?stp=dst-jpegr_e35_tt6&_nc_cat=109&ig_cache_key=Mzk0NTU4NDUxMDUwODM5MjI1Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNBUk9VU0VMX0lURU0ueHBpZHMuMzAyNC5oZHIucmVndWxhcl9waG90by5DMyJ9&_nc_ohc=w_tkuENoSkkQ7kNvwGNhhkp&_nc_oc=AdreG79wFM0VyREcQfp-FIM4btiu6wTpFF9rjTBJy7rOy3Hl1jXBaxIHBm25jzSkdhg&_nc_zt=23&_nc_ht=scontent-phx1-1.cdninstagram.com&_nc_gid=clv6joZMJjTUdpcyrs-A9A&_nc_ss=72a8c&oh=00_AQAguB9tNl94_iwgMotw-eMLpbS50TUIECd39Kdgk5K2cg&oe=6A6D817C', 'video_url': None, 'timestamp': '2026-07-20T18:01:53.000Z', 'hashtags': ['glambox', 'коробкакрасоты', 'боксы'], 'mentions': []}, {'caption': 'Это не генетика и не «повезло». \nЭто постоянная работа над собой, полезные привычки, спорт, питание и всё это обязательно в комплексе с Голдлайн плюс ☀️\n\n#голдлайнплюс #голдлайн #худеем #зож', 'likes': -1, 'comments': 54, 'image_url': 'https://scontent-fco2-1.cdninstagram.com/v/t51.71878-15/751591569_2112547436325343_2774782023586357929_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-fco2-1.cdninstagram.com&_nc_cat=107&_nc_oc=Q6cZ2gF6q-jpk0f5I2wsuJx61gTioJ77OwWKqCjxRwxdUkCNBlNELJoV5vlOMF2NeuKsfa8&_nc_ohc=Q1tQRulX9XQQ7kNvwG1F0pY&_nc_gid=-78GIDI_UiyifbEdsEnkoA&edm=ADp7STQBAAAA&ccb=7-5&oh=00_AQBXkOBdRrZlS4bFqz6HKuSGTk0garU-s9bxlMT9WGVkwg&oe=6A6D85F0&_nc_sid=c6f216', 'video_url': 'https://scontent-mxp2-1.cdninstagram.com/o1/v/t2/f2/m86/AQNeCo9yXIbCtXGIy235Ey5lVflHSHt0iFF-5AsMf_0CwXnGee1JqPhe8KP8AVCjzz4bx0ctHeYFhYQ63Med6J-w85zzUJvtqdVgRb8.mp4?_nc_cat=105&_nc_sid=5e9851&_nc_ht=scontent-mxp2-1.cdninstagram.com&_nc_ohc=bCCd5l6jgQ4Q7kNvwE0fWm6&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTY5MjY5ODI0MTk0NTgxMCwiYXNzZXRfYWdlX2RheXMiOjUsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjo1NiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=52e429d5de9129fb&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9DRTQ1MjRCMDhCNDc1RDUxNDQxNUY3NEI1NTlFMEM5MV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzcyNDE4RUJEMjUyQ0M2MTNCOERGOUQ0NTZEMTkwMDlCX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACakw-LWgOCBBhUCKAJDMywXQExIcrAgxJwYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=lxyACZ3fSEf1Yn1Mwnx50w&_nc_ss=72a8c&_nc_zt=28&oh=00_AQCDEHaOuevy8vFQZKT5fPj1TmbhTtwZo-cC84480wkXHA&oe=6A69BA56', 'timestamp': '2026-07-22T12:05:22.000Z', 'hashtags': ['голдлайнплюс', 'голдлайн', 'худеем', 'зож'], 'mentions': []}, {'caption': 'Идеальные 🧡\nСпрей из ЗЯ #19000516920\nМаска против желтизны из ЗЯ #19000516917', 'likes': -1, 'comments': 4, 'image_url': 'https://scontent-hou1-1.cdninstagram.com/v/t51.82787-15/742198124_18105236003274677_6781067949190043006_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=105&ig_cache_key=Mzk0MzUyOTk3ODc3NzQ1NjM5OTE4MTA1MjM2MDAwMjc0Njc3.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjcyMC5zZHIudmlkZW9fZGVmYXVsdF9jb3Zlcl9mcmFtZS5DMyJ9&_nc_ohc=Cy_tDIcwKEAQ7kNvwETg-U_&_nc_oc=AdrxMdKkc6A06Os2egiT6QDHQcke8hPX9sYeZo4KfHeiMeXawSPdt7_3RmqJDa4l7eE&_nc_zt=23&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_gid=sIZujPYuL6AXUoq39dCEEg&_nc_ss=7ca8c&oh=00_AQD7IKYQmpPwpMTH5ZIzf63Pf5qTDXdwSClAJs9MxTe7Zg&oe=6A6D85A0', 'video_url': 'https://scontent-hou1-1.cdninstagram.com/o1/v/t2/f2/m86/AQPT2cB_SZ8GzzWC7ZT3WwPRglAPYVuIe2BxngtdujXjBb_CnPQBsyQCeVGuUMDIRROgyfzJMencDw3zejnLgrCW39MaQiqPMOa3wSc.mp4?_nc_cat=111&_nc_sid=5e9851&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_ohc=oMOqMK6UzlcQ7kNvwHSnCRj&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTM1NTU4MTc1MjgyNzA3NywiYXNzZXRfYWdlX2RheXMiOjksInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjo3LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=b02ccc988cde7fb8&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC84RTRCM0ZBQUQ4NTcxQzBEOURDM0MwQzQ4RDFBMkZBOV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0Y0NDRBMzE1QTE2RkMxOEQ3OTc0MjcxOTQ4NTc4MTgxX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaK87qNn7noBBUCKAJDMywXQB4AAAAAAAAYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=sIZujPYuL6AXUoq39dCEEg&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQCbI2jmyK3Tn3HOYuQFTJzLKtuamkG9LuL7O4luV2TRJA&oe=6A699DEC', 'timestamp': '2026-07-17T21:57:32.000Z', 'hashtags': ['19000516920', '19000516917'], 'mentions': []}, {'caption': 'Это чудо находка за чуть больше 200₽ 😱💥💥💥\nНа вб #238539583', 'likes': -1, 'comments': 18, 'image_url': 'https://instagram.fmel5-1.fna.fbcdn.net/v/t51.71878-15/753534586_1038981562210353_5565916467336924955_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=109&ig_cache_key=Mzk0NjIyNzI3NzY0NzMzNzYzOQ%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjY0MC5zZHIudmlkZW9fbmZyYW1lX2NvdmVyX2ZyYW1lLkMzIn0%3D&_nc_ohc=O42rgaP37FoQ7kNvwFCuCH5&_nc_oc=Adp9_2vllJl-2aSrCsSGoMi53N4UooF8EzFp-k2NBSArH7FxsOv86SNeKIltHMdmURU&_nc_zt=23&_nc_ht=instagram.fmel5-1.fna&_nc_gid=OtmDZDxwxzhuujRre10GwQ&_nc_ss=7ca8c&oh=00_AQAsiClqTuAPqT0SEXZF3nSKU6whmrPEzOO7KrlCXabe8w&oe=6A6DAB7E', 'video_url': 'https://instagram.fmel5-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQN73ZjtBU7NIYqzC0dWdcGY_3eX0XO2bQhSZneWbOI6dzYjt4BT61WOiRcJao0ewPw2H0EE-3MlkhNcNZqW3vKaH06x6OU5K5HFI4g.mp4?_nc_cat=110&_nc_oc=AdpZ8OQACehL00VzEGwl8WBv_DAPd3ZyYjW27QNf_nNSik4TNvq8m23CWzVgy6ibjNI&_nc_sid=5e9851&_nc_ht=instagram.fmel5-1.fna.fbcdn.net&_nc_ohc=89vbBKi5FE0Q7kNvwEPmsMa&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTA4ODA5NTIzMDIwNzQzNiwiYXNzZXRfYWdlX2RheXMiOjYsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjo0MywidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=3a09d33eba82bd1&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9CNjQzRkIzOUI1Rjc0MzE2RkY1Q0U0MkZBRDQ1QkE4RV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0MxNDJEOUFFNjUxMTY5RTY4OUYyMEU3N0QwMEU0NkI3X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaYl-2avefuAxUCKAJDMywXQEWu2RaHKwIYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=OtmDZDxwxzhuujRre10GwQ&_nc_ss=7ca8c&_nc_zt=28&oh=00_AQCeYQiTJsDUyVEcKG9lFKtLFZAqwn8i_nuA1YcrXfpoeg&oe=6A69A1C3', 'timestamp': '2026-07-21T15:17:34.000Z', 'hashtags': ['238539583'], 'mentions': []}, {'caption': 'ВЕСЬ ИЮЛЬ В @chicko_tula 3 АПЕРОЛЯ ПО ЦЕНЕ 1 🧡🍹\n\nЧастичка Азии в самом центре Тулы ☀️\n\n📍ул.Советская,д.60 @chicko_tula \n\n#местатулы #блогертула #тула #кафетула #кудасходитьвтуле', 'likes': -1, 'comments': 4, 'image_url': 'https://scontent-waw2-1.cdninstagram.com/v/t51.71878-15/748330553_3490954691080338_7717752385874917803_n.jpg?stp=dst-jpg_e15_tt6&_nc_cat=108&ig_cache_key=Mzk0MzMwMTM3Nzk5MzkwNDUyOA%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLnhwaWRzLjY0MC5zZHIudmlkZW9fbmZyYW1lX2NvdmVyX2ZyYW1lLkMzIn0%3D&_nc_ohc=JhCs9u9Fk1cQ7kNvwGzanbk&_nc_oc=AdoG2AGdJSuBeaOohuaFCUMTVYxWkprG1pD5kq7-Ex2_2uAkIT4nI_vqT2qyLLgv_6Y&_nc_zt=23&_nc_ht=scontent-waw2-1.cdninstagram.com&_nc_gid=HJWUrhcD9LD5guAaKX1JMw&_nc_ss=72a8c&oh=00_AQB03Q0vbI8WwZop3RdglGrwq7xaUZRmgeVXB8Twzgm_AA&oe=6A6DA2E3', 'video_url': 'https://scontent-waw2-2.cdninstagram.com/o1/v/t2/f2/m86/AQOnwySyw1nMmjrCT68uyDBxV83jMiny8ywNuVVlBXkz82ItvHiGCpNs15mvhq84cr5PsC6eNhmMAbJ23X7scOfgFVm6TaIyDZySRSQ.mp4?_nc_cat=105&_nc_sid=5e9851&_nc_ht=scontent-waw2-2.cdninstagram.com&_nc_ohc=x7LhB_etl_UQ7kNvwGjxaSa&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MjI0MTE1NTQxNjYzNTg3MCwiYXNzZXRfYWdlX2RheXMiOjEwLCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6MjQsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=7030d330c73b53fe&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC80NzRCMTA2Mjk1MEE0M0EyOUI1Qzc3QzMzOUE2NUVCMF92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzdFNDU5NTQwREU0MjM2NjM5QjM3MzJGNzgyNzYwNEJBX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACa85_WHtZT7BxUCKAJDMywXQDj3S8an754YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gi

Сохраняю все данные в json:

In [61]:
import json

with open(
    "instagram_bloggers_full.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        result,
        f,
        ensure_ascii=False,
        indent=2
    )

#2. Аналитика

Считаю среднее количество лайков, комментариев, хэштегов, ER, среднюю длину постов

In [63]:
import numpy as np

#среднее кол-во лайков
def avg_likes(posts):

    likes = [
        p.get("likes", 0)
        for p in posts
    ]

    return np.mean(likes)

In [64]:
#среднее кол-во комментариев

def avg_comments(posts):

    comments = [
        p.get("comments", 0)
        for p in posts
    ]

    return np.mean(comments)

In [71]:
def calculate_er(data):

    followers = data.get(
        "followers",
        0
    )

    if followers == 0:
        return 0


    avg_like = avg_likes(
        data["posts"]
    )

    avg_comment = avg_comments(
        data["posts"]
    )


    return (
        (avg_like + avg_comment)
        /
        followers
        *
        100
    )

In [84]:

def avg_caption_length(posts):

    lengths = []

    for p in posts:

        caption = p.get("caption") or ""

        lengths.append(
            len(caption)
        )

    return np.mean(lengths) if lengths else 0



def avg_hashtags(posts):

    counts = []

    for p in posts:

        hashtags = p.get("hashtags") or []

        counts.append(
            len(hashtags)
        )

    return np.mean(counts) if counts else 0

In [85]:
analytics = []


for username, data in result.items():

    posts = data.get("posts", [])

    if not posts:
        continue


    analytics.append({

        "username": username,

        "followers": data.get("followers", 0),
        "following": data.get("following", 0),
        "posts_count": data.get("posts_count", 0),

        "avg_likes": avg_likes(posts),
        "avg_comments": avg_comments(posts),

        "ER": calculate_er(data),

        "avg_caption_length": avg_caption_length(posts),

        "avg_hashtags": avg_hashtags(posts),

        "posts_analyzed": len(posts)
    })

In [86]:
import pandas as pd


df = pd.DataFrame(
    analytics
)


df.head()

,username,followers,following,posts_count,avg_likes,avg_comments,ER,video_ratio,avg_caption_length,avg_hashtags,posts_analyzed
0,daria_grogulenko,5364,244,159,5.700000,0.350000,0.112789,1.000000,147.850000,3.35,20
1,apple,36961487,9,1355,53206.950000,515.500000,0.145347,0.750000,197.000000,1.05,20
2,v.m.beauty_blog,205852,308,1290,121.000000,11.200000,0.064221,0.950000,181.750000,2.00,20
3,armlilitka,88310,680,1609,11553.400000,189.200000,13.297022,1.000000,479.550000,4.05,20
4,nike,291697549,264,1667,315905.944444,2699.444444,0.109225,0.444444,133.555556,0.00,18

In [68]:
df.sort_values(
    "ER",
    ascending=False
).head(20)

,username,followers,following,posts_count,avg_likes,avg_comments,ER,posts_analyzed
12,aida.mixx,49718,1883,1152,17298.200000,124.800000,35.043646,20
3,armlilitka,88310,680,1609,11553.400000,189.200000,13.297022,20
9,dddinaaaaaa,7974,1076,72,967.833333,70.333333,13.019396,18
10,llaurraiiam,11592,631,220,607.950000,38.300000,5.574965,20
19,gkaterinka___,21811,2966,718,432.500000,193.000000,2.867819,2
22,zari.ishikhovaa,20539,1730,205,521.250000,25.950000,2.664200,20
23,ninooochka2.0,27653,1704,79,591.600000,29.050000,2.244422,20
5,jd_cosm,138306,461,2244,1598.150000,17.100000,1.167881,20
16,janestetsiura,29750,348,138,292.150000,6.850000,1.005042,20
20,bazhenova.studio,1843,669,968,16.000000,2.000000,0.976668,1
11,kristi_naxodka,147408,423,510,1177.200000,57.350000,0.837505,20
13,anetboss_,148609,167,1377,1197.150000,27.150000,0.823840,20
8,juliar_r,256847,320,211,1661.950000,24.450000,0.656578,20
15,nikebasketball,15587866,332,1601,90218.000000,265.000000,0.580471,1
21,kotova.live,48628,258,2395,225.500000,26.050000,0.517295,20
18,_kate_bruni,322346,630,1321,1352.111111,21.166667,0.426026,18
14,yunglolaa,77209,471,764,267.750000,12.350000,0.362782,20
17,bazhenova_alenaa,17735,90,3299,48.526316,3.526316,0.293502,19
1,apple,36961487,9,1355,53206.950000,515.500000,0.145347,20
7,nikefootball,44886288,617,2891,56311.000000,372.000000,0.126281,1

Добавляю еще некоторые статистики:
доля рекламных постов;
количество упоминаний брендов;
частота публикаций;
медианный ER;
распределение форматов контента.

1. Доля рекламных постов

In [87]:
AD_WORDS = [
    "реклама",
    "#реклама",
    "ad",
    "#ad",
    "партнерство",
    "партнёрство",
    "сотрудничество",
    "промокод",
    "по промокоду",
    "подарок",
    "подарили",
    "от бренда",
    "collab"
]

In [88]:
def ad_ratio(posts):

    if not posts:
        return 0

    ad_posts = 0

    for p in posts:

        caption = (
            p.get("caption") or ""
        ).lower()


        if any(
            word in caption
            for word in AD_WORDS
        ):
            ad_posts += 1


    return ad_posts / len(posts)

2. Количество упоминаний брендов

In [89]:
def avg_mentions(posts):

    values = []

    for p in posts:

        mentions = p.get(
            "mentions",
            []
        )

        values.append(
            len(mentions)
        )

    return np.mean(values) if values else 0

3. Частота публикаций

In [90]:
from datetime import datetime


def posting_frequency(posts):

    if len(posts) < 2:
        return 0


    dates = []

    for p in posts:

        date = p.get(
            "timestamp"
        )

        if date:
            dates.append(
                datetime.fromisoformat(
                    date.replace("Z", "+00:00")
                )
            )


    if len(dates) < 2:
        return 0


    days = (
        max(dates) - min(dates)
    ).days


    if days == 0:
        return len(posts)


    return len(posts) / days * 30

4. Медианный ER
Средний ER может ломаться из-за одного вирусного ролика.

In [91]:
def median_er(data):

    followers = data.get(
        "followers",
        0
    )

    if followers == 0:
        return 0


    ers = []


    for p in data["posts"]:

        likes = p.get(
            "likes",
            0
        )

        comments = p.get(
            "comments",
            0
        )


        er = (
            (likes + comments)
            /
            followers
            *
            100
        )

        ers.append(er)


    return np.median(ers) if ers else 0

5. Распределение форматов

Reels;
фото.

In [93]:
def content_types(posts):

    total = len(posts)

    if total == 0:
        return {
            "video_ratio": 0,
            "photo_ratio": 0
        }


    videos = sum(
        1
        for p in posts
        if p.get("video_url")
    )


    return {

        "video_ratio":
            videos / total,

        "photo_ratio":
            (total - videos) / total
    }

6. Добавляем все в analytics

In [94]:
analytics = []


for username, data in result.items():

    posts = data.get("posts", [])

    if not posts:
        continue


    formats = content_types(posts)


    analytics.append({

        "username": username,

        # профиль
        "followers": data.get(
            "followers",
            0
        ),

        "following": data.get(
            "following",
            0
        ),

        "posts_count": data.get(
            "posts_count",
            0
        ),


        # активность
        "avg_likes": avg_likes(posts),

        "avg_comments": avg_comments(posts),

        "ER": calculate_er(data),

        "median_ER": median_er(data),


        # контент
        "video_ratio":
            formats["video_ratio"],

        "photo_ratio":
            formats["photo_ratio"],


        "avg_caption_length":
            avg_caption_length(posts),

        "avg_hashtags":
            avg_hashtags(posts),


        # сотрудничество
        "ad_ratio":
            ad_ratio(posts),

        "avg_mentions":
            avg_mentions(posts),


        # регулярность
        "posts_per_month":
            posting_frequency(posts),


        "posts_analyzed":
            len(posts)
    })

In [95]:
analytics = []


for username, data in result.items():

    posts = data.get("posts", [])

    if not posts:
        continue


    formats = content_types(posts)


    analytics.append({

        "username": username,

        # профиль
        "followers": data.get(
            "followers",
            0
        ),

        "following": data.get(
            "following",
            0
        ),

        "posts_count": data.get(
            "posts_count",
            0
        ),


        # активность
        "avg_likes": avg_likes(posts),

        "avg_comments": avg_comments(posts),

        "ER": calculate_er(data),

        "median_ER": median_er(data),


        # контент
        "video_ratio":
            formats["video_ratio"],

        "photo_ratio":
            formats["photo_ratio"],


        "avg_caption_length":
            avg_caption_length(posts),

        "avg_hashtags":
            avg_hashtags(posts),


        # сотрудничество
        "ad_ratio":
            ad_ratio(posts),

        "avg_mentions":
            avg_mentions(posts),


        # регулярность
        "posts_per_month":
            posting_frequency(posts),


        "posts_analyzed":
            len(posts)
    })

In [96]:
df = pd.DataFrame(
    analytics
)


df.head()

,username,followers,following,posts_count,avg_likes,avg_comments,ER,median_ER,video_ratio,photo_ratio,avg_caption_length,avg_hashtags,ad_ratio,avg_mentions,posts_per_month,posts_analyzed
0,daria_grogulenko,5364,244,159,5.700000,0.350000,0.112789,0.093214,1.000000,0.000000,147.850000,3.35,0.150000,1.300000,2.127660,20
1,apple,36961487,9,1355,53206.950000,515.500000,0.145347,0.091585,0.750000,0.250000,197.000000,1.05,0.300000,1.350000,13.636364,20
2,v.m.beauty_blog,205852,308,1290,121.000000,11.200000,0.064221,0.001943,0.950000,0.050000,181.750000,2.00,0.000000,0.300000,60.000000,20
3,armlilitka,88310,680,1609,11553.400000,189.200000,13.297022,2.683162,1.000000,0.000000,479.550000,4.05,0.050000,0.550000,0.936037,20
4,nike,291697549,264,1667,315905.944444,2699.444444,0.109225,0.067544,0.444444,0.555556,133.555556,0.00,0.055556,0.833333,13.500000,18

Собираю компактный json для промта аналитики:

In [97]:
ai_profiles = []


for username, data in result.items():

    posts = data.get("posts", [])

    if not posts:
        continue


    analytics_row = df[
        df["username"] == username
    ].iloc[0]


    profile = {

        "username": username,


        "profile": {

            "name":
                data.get("full_name"),

            "bio":
                data.get("bio"),

            "followers":
                data.get("followers"),

            "category":
                data.get("category")

        },


        "metrics": {

            "ER":
                round(
                    analytics_row["ER"],
                    2
                ),

            "median_ER":
                round(
                    analytics_row["median_ER"],
                    2
                ),

            "avg_likes":
                round(
                    analytics_row["avg_likes"]
                ),

            "video_ratio":
                round(
                    analytics_row["video_ratio"],
                    2
                ),

            "ad_ratio":
                round(
                    analytics_row["ad_ratio"],
                    2
                ),

            "posts_per_month":
                round(
                    analytics_row["posts_per_month"],
                    1
                )

        },


        "sample_posts": [

            {
                "caption":
                    p.get("caption"),

                "hashtags":
                    p.get("hashtags")

            }

            for p in posts[:5]

        ]

    }


    ai_profiles.append(profile)

In [98]:
print(
    ai_profiles[0]
)

{'username': 'daria_grogulenko', 'profile': {'name': 'Дарья | Обзоры с WILDBERRIES | женственность', 'bio': 'Стильные образы в REELS\nБольше находок в моем телеграмме👇🏼\n📍Moscow | Московский \nТг канал:', 'followers': 5364, 'category': None}, 'metrics': {'ER': np.float64(0.11), 'median_ER': np.float64(0.09), 'avg_likes': 6, 'video_ratio': np.float64(1.0), 'ad_ratio': np.float64(0.15), 'posts_per_month': np.float64(2.1)}, 'sample_posts': [{'caption': 'Девочки, мы?🤣 \nНа видео продукты от @mixit_ru 🩷\n\nАртикул на обертывание ВБ:👇🏼\n#ww114906', 'hashtags': ['ww114906']}, {'caption': '@daria_grogulenko больше обзоров у меня в профиле!🤍\n\n📎Артикул 299373468', 'hashtags': []}, {'caption': 'А как вы пользуетесь скрабом?\nАртикул на скраб от @mixit_ru 🫶🏻👇🏼\n\nВБ: #ww114862 \nОзон: 1843395876\n\n@daria_grogulenko больше обзоров у меня в профиле, подпишись, чтобы не пропустить🫶🏻\n#находкивб #вб #распаковка #юмор', 'hashtags': ['ww114862', 'находкивб', 'вб', 'распаковка', 'юмор']}, {'caption': '@daria_grogulenko больше обзоров у меня в профиле!🤍\n\n#вб #распаковка #образ #стиль', 'hashtags': ['вб', 'распаковка', 'образ', 'стиль']}, {'caption': 'На видео продукты от @mixit_ru 🫶🏻\n\nИдеальная пудра для лица артикул Вб:👇🏼\n#ww114857 \n\n@daria_grogulenko больше обзоров у меня в профиле, подпишись, чтобы не пропустить🫶🏻\n#вб #распаковка #образ #стиль', 'hashtags': ['ww114857', 'вб', 'распаковка', 'образ', 'стиль']}]}

In [125]:
import json

with open(
    "ai_profiles.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        ai_profiles,
        f,
        ensure_ascii=False,
        indent=2
    )

In [126]:
from google.colab import files

files.download(
    "ai_profiles.json"
)

#3. Промты для LLM

Промтф сформированы gpt по описнной задаче (это best practice, llm генерируют промты лучше человека)

###**Запрос №1 — найти закономерности**
prompt = """
Ты анализируешь базу из 24 Instagram блогеров,
которые уже были отобраны как подходящие для бренда.

Изучи данные и найди общие признаки.

Проанализируй:

1. Тематики блогеров
2. Общий стиль подачи
3. Тип аудитории
4. Особенности bio
5. Стиль написания постов
6. Частоту рекламы
7. Форматы контента
8. Метрики вовлеченности

Найди повторяющиеся закономерности.

Не описывай каждого блогера отдельно.
Создай обобщенный портрет.

Вот данные:

{DATA}
"""

Здесь DATA - это json из предыдущего пункта

### **Запрос №2 — создать профиль идеального кандидата**
prompt = """
На основе анализа успешных блогеров создай
портрет идеального Instagram блогера для поиска новых кандидатов.

Опиши:

1. Размер аудитории
2. Минимальный ER
3. Тематики
4. Визуальный стиль
5. Стиль общения
6. Тип контента
7. Как выглядит идеальная bio
8. Какие бренды ему подходят
9. Какие признаки использовать для поиска похожих аккаунтов

Формат:

- Критерий
- Почему важен
- Как измерять

Используй анализ:
{ANALYSIS}
"""

Здесь ANALYSIS - это аналитика предыдущего промта

*Время выполнения до этого момента: 6 часов*